# Static holdings database for top Indian equity mutual funds
# Source: Publicly disclosed monthly portfolios (May 2026)
# Weights are approximate % to NAV for equity holdings only

FUND_HOLDINGS = {
    "axis bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.8},
        {"stock_name": "ICICI Bank", "weight_percent": 8.4},
        {"stock_name": "Infosys", "weight_percent": 7.2},
        {"stock_name": "Reliance Industries", "weight_percent": 6.5},
        {"stock_name": "Bajaj Finance", "weight_percent": 5.1},
        {"stock_name": "TCS", "weight_percent": 4.8},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 4.2},
        {"stock_name": "Axis Bank", "weight_percent": 3.9},
        {"stock_name": "Larsen & Toubro", "weight_percent": 3.6},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.3},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.8},
        {"stock_name": "Avenue Supermarts", "weight_percent": 2.5},
        {"stock_name": "Titan Company", "weight_percent": 2.3},
        {"stock_name": "Asian Paints", "weight_percent": 2.1},
        {"stock_name": "HUL", "weight_percent": 1.9},
    ],
    "mirae asset large cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.96},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.19},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.4},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 5.32},
        {"stock_name": "Infosys Ltd", "weight_percent": 4.08},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.57},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.46},
        {"stock_name": "State Bank of India", "weight_percent": 2.93},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.55},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.43},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.43},
        {"stock_name": "ITC Ltd", "weight_percent": 2.42},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 2.09},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.79},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.7},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 1.61},
        {"stock_name": "Britannia Industries Ltd", "weight_percent": 1.45},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 1.39},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 1.35},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.32},
    ],
    "hdfc flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.83},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 6.84},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 6.48},
        {"stock_name": "State Bank of India", "weight_percent": 4.22},
        {"stock_name": "SBI Life Insurance Co Ltd", "weight_percent": 3.76},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.55},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.43},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.96},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.91},
        {"stock_name": "Cipla Ltd", "weight_percent": 2.89},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 2.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.73},
        {"stock_name": "Power Grid Corp Of India Ltd", "weight_percent": 2.51},
        {"stock_name": "HCL Technologies Ltd", "weight_percent": 2.47},
        {"stock_name": "Eicher Motors Ltd", "weight_percent": 2.46},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 2.01},
        {"stock_name": "Bajaj Auto Ltd", "weight_percent": 1.78},
        {"stock_name": "JSW Steel Ltd", "weight_percent": 1.72},
        {"stock_name": "Hyundai Motor India Ltd", "weight_percent": 1.7},
        {"stock_name": "Piramal Pharma Ltd", "weight_percent": 1.53},
    ],
    "hdfc top 100 fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 10.1},
        {"stock_name": "HDFC Bank", "weight_percent": 9.4},
        {"stock_name": "Reliance Industries", "weight_percent": 7.2},
        {"stock_name": "Infosys", "weight_percent": 6.1},
        {"stock_name": "Axis Bank", "weight_percent": 5.5},
        {"stock_name": "State Bank of India", "weight_percent": 5.0},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.6},
        {"stock_name": "TCS", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.4},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.7},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.4},
        {"stock_name": "HCL Technologies", "weight_percent": 2.1},
        {"stock_name": "NTPC", "weight_percent": 1.9},
    ],
    "sbi bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.6},
        {"stock_name": "ICICI Bank", "weight_percent": 8.2},
        {"stock_name": "Reliance Industries", "weight_percent": 7.1},
        {"stock_name": "Infosys", "weight_percent": 6.3},
        {"stock_name": "Larsen & Toubro", "weight_percent": 5.2},
        {"stock_name": "Axis Bank", "weight_percent": 4.7},
        {"stock_name": "TCS", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.9},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "State Bank of India", "weight_percent": 3.2},
        {"stock_name": "HUL", "weight_percent": 2.8},
        {"stock_name": "ITC", "weight_percent": 2.5},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.2},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.0},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "icici prudential bluechip fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.72},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.46},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.41},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.38},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 4.67},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.34},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.6},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 3.55},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.69},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.65},
        {"stock_name": "NTPC Ltd", "weight_percent": 2.38},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.34},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 2.02},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 1.83},
        {"stock_name": "Hero MotoCorp Ltd", "weight_percent": 1.59},
        {"stock_name": "DLF Ltd", "weight_percent": 1.32},
        {"stock_name": "Oil & Natural Gas Corp Ltd", "weight_percent": 1.25},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.21},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 1.16},
        {"stock_name": "Hindustan Aeronautics Ltd Ordinary Shares", "weight_percent": 1.11},
    ],
    "parag parikh flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 7.8},
        {"stock_name": "Bajaj Holdings", "weight_percent": 6.2},
        {"stock_name": "ITC", "weight_percent": 5.9},
        {"stock_name": "Power Grid Corporation", "weight_percent": 5.3},
        {"stock_name": "Coal India", "weight_percent": 4.8},
        {"stock_name": "ICICI Bank", "weight_percent": 4.5},
        {"stock_name": "Axis Bank", "weight_percent": 4.1},
        {"stock_name": "HCL Technologies", "weight_percent": 3.7},
        {"stock_name": "Alphabet Inc (US)", "weight_percent": 3.4},
        {"stock_name": "Meta Platforms (US)", "weight_percent": 3.1},
        {"stock_name": "Microsoft (US)", "weight_percent": 2.8},
        {"stock_name": "Amazon (US)", "weight_percent": 2.5},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.2},
        {"stock_name": "CDSL", "weight_percent": 1.9},
        {"stock_name": "Zydus Lifesciences", "weight_percent": 1.7},
    ],
    "kotak flexicap fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 8.5},
        {"stock_name": "HDFC Bank", "weight_percent": 7.9},
        {"stock_name": "Infosys", "weight_percent": 6.8},
        {"stock_name": "Reliance Industries", "weight_percent": 6.2},
        {"stock_name": "Axis Bank", "weight_percent": 5.1},
        {"stock_name": "TCS", "weight_percent": 4.7},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bajaj Finance", "weight_percent": 3.4},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.1},
        {"stock_name": "State Bank of India", "weight_percent": 2.7},
        {"stock_name": "HUL", "weight_percent": 2.4},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Titan Company", "weight_percent": 1.8},
        {"stock_name": "ITC", "weight_percent": 1.6},
    ],
    "nippon india large cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.3},
        {"stock_name": "ICICI Bank", "weight_percent": 8.1},
        {"stock_name": "Reliance Industries", "weight_percent": 7.5},
        {"stock_name": "Infosys", "weight_percent": 6.4},
        {"stock_name": "State Bank of India", "weight_percent": 5.6},
        {"stock_name": "Larsen & Toubro", "weight_percent": 5.0},
        {"stock_name": "TCS", "weight_percent": 4.5},
        {"stock_name": "Axis Bank", "weight_percent": 4.0},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 2.8},
        {"stock_name": "NTPC", "weight_percent": 2.4},
        {"stock_name": "Power Grid Corporation", "weight_percent": 2.1},
        {"stock_name": "HCL Technologies", "weight_percent": 1.9},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "canara robeco bluechip equity fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.1},
        {"stock_name": "ICICI Bank", "weight_percent": 8.3},
        {"stock_name": "Infosys", "weight_percent": 7.0},
        {"stock_name": "Reliance Industries", "weight_percent": 6.4},
        {"stock_name": "TCS", "weight_percent": 5.5},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.8},
        {"stock_name": "Axis Bank", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.7},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.3},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.9},
        {"stock_name": "ITC", "weight_percent": 2.6},
        {"stock_name": "HUL", "weight_percent": 2.3},
        {"stock_name": "State Bank of India", "weight_percent": 2.0},
        {"stock_name": "HCL Technologies", "weight_percent": 1.8},
        {"stock_name": "Asian Paints", "weight_percent": 1.6},
    ],
    "sbi small cap fund": [
        {"stock_name": "Ather Energy Ltd", "weight_percent": 5.18},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 3.11},
        {"stock_name": "Honeywell Automation India Ltd", "weight_percent": 2.83},
        {"stock_name": "Kalpataru Projects International Ltd", "weight_percent": 2.76},
        {"stock_name": "ZF Commercial Vehicle Control Systems India Ltd", "weight_percent": 2.75},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 2.69},
        {"stock_name": "Belrise Industries Ltd", "weight_percent": 2.52},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.5},
        {"stock_name": "Sundaram Fasteners Ltd", "weight_percent": 2.3},
        {"stock_name": "SBFC Finance Ltd", "weight_percent": 2.25},
        {"stock_name": "Kajaria Ceramics Ltd", "weight_percent": 2.01},
        {"stock_name": "K.P.R. Mill Ltd", "weight_percent": 1.99},
        {"stock_name": "Deepak Fertilisers & Petrochemicals Corp Ltd", "weight_percent": 1.98},
        {"stock_name": "Anand Rathi Wealth Ltd", "weight_percent": 1.94},
        {"stock_name": "DOMS Industries Ltd", "weight_percent": 1.93},
        {"stock_name": "Chalet Hotels Ltd", "weight_percent": 1.89},
        {"stock_name": "E I D Parry India Ltd", "weight_percent": 1.88},
        {"stock_name": "Urban Co Ltd", "weight_percent": 1.72},
        {"stock_name": "Finolex Industries Ltd", "weight_percent": 1.72},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.66},
    ],
    "nippon india small cap fund": [
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.93},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 1.77},
        {"stock_name": "TD Power Systems Ltd", "weight_percent": 1.71},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.57},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 1.55},
        {"stock_name": "State Bank of India", "weight_percent": 1.29},
        {"stock_name": "NLC India Ltd", "weight_percent": 1.26},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 1.23},
        {"stock_name": "Zydus Wellness Ltd", "weight_percent": 1.17},
        {"stock_name": "Tube Investments of India Ltd", "weight_percent": 1.05},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.03},
        {"stock_name": "Kirloskar Brothers Ltd", "weight_percent": 0.99},
        {"stock_name": "MTAR Technologies Ltd", "weight_percent": 0.98},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 0.96},
        {"stock_name": "Sundaram Fasteners Ltd", "weight_percent": 0.95},
        {"stock_name": "Sai Life Sciences Ltd", "weight_percent": 0.91},
        {"stock_name": "Emami Ltd", "weight_percent": 0.9},
        {"stock_name": "Whirlpool of India Ltd", "weight_percent": 0.88},
        {"stock_name": "Kirloskar Pneumatic Co Ltd", "weight_percent": 0.87},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 0.86},
    ],
    "axis small cap fund": [
        {"stock_name": "Kaynes Technology", "weight_percent": 3.4},
        {"stock_name": "Cholamandalam Financial Holdings", "weight_percent": 3.1},
        {"stock_name": "Affle India", "weight_percent": 2.9},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.7},
        {"stock_name": "Dixon Technologies", "weight_percent": 2.5},
        {"stock_name": "Suven Pharmaceuticals", "weight_percent": 2.3},
        {"stock_name": "Techno Electric & Engineering", "weight_percent": 2.1},
        {"stock_name": "Caplin Point Laboratories", "weight_percent": 2.0},
        {"stock_name": "Garware Technical Fibres", "weight_percent": 1.8},
        {"stock_name": "Vinati Organics", "weight_percent": 1.7},
        {"stock_name": "Safari Industries", "weight_percent": 1.6},
        {"stock_name": "Tube Investments of India", "weight_percent": 1.5},
        {"stock_name": "V-Guard Industries", "weight_percent": 1.4},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.3},
        {"stock_name": "Dodla Dairy", "weight_percent": 1.2},
    ],
    "bandhan small cap fund": [
        {"stock_name": "Nucleus Software Exports", "weight_percent": 3.2},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.9},
        {"stock_name": "Suven Pharmaceuticals", "weight_percent": 2.7},
        {"stock_name": "Dodla Dairy", "weight_percent": 2.5},
        {"stock_name": "Caplin Point Laboratories", "weight_percent": 2.3},
        {"stock_name": "Safari Industries", "weight_percent": 2.1},
        {"stock_name": "V-Guard Industries", "weight_percent": 1.9},
        {"stock_name": "Repco Home Finance", "weight_percent": 1.8},
        {"stock_name": "Craftsman Automation", "weight_percent": 1.7},
        {"stock_name": "Brigade Enterprises", "weight_percent": 1.6},
        {"stock_name": "HDFC Bank", "weight_percent": 0.55},
        {"stock_name": "Mold-Tek Packaging", "weight_percent": 1.5},
        {"stock_name": "Chalet Hotels", "weight_percent": 1.4},
        {"stock_name": "Marksans Pharma", "weight_percent": 1.3},
        {"stock_name": "Techno Electric & Engineering", "weight_percent": 1.2},
    ],
    "quant small cap fund": [
        {"stock_name": "Reliance Industries", "weight_percent": 5.2},
        {"stock_name": "IRB Infrastructure Developers", "weight_percent": 3.8},
        {"stock_name": "Waaree Energies", "weight_percent": 3.5},
        {"stock_name": "Jio Financial Services", "weight_percent": 3.2},
        {"stock_name": "Bikaji Foods", "weight_percent": 2.9},
        {"stock_name": "Patanjali Foods", "weight_percent": 2.7},
        {"stock_name": "GNFC", "weight_percent": 2.5},
        {"stock_name": "Aarti Industries", "weight_percent": 2.3},
        {"stock_name": "RBL Bank", "weight_percent": 2.1},
        {"stock_name": "Inox Wind", "weight_percent": 2.0},
        {"stock_name": "SAIL", "weight_percent": 1.8},
        {"stock_name": "Manappuram Finance", "weight_percent": 1.7},
        {"stock_name": "Tata Teleservices", "weight_percent": 1.5},
        {"stock_name": "Trident", "weight_percent": 1.4},
        {"stock_name": "Strides Pharma", "weight_percent": 1.3},
    ],
    "hdfc mid-cap opportunities fund": [
        {"stock_name": "Cholamandalam Investment", "weight_percent": 3.8},
        {"stock_name": "Persistent Systems", "weight_percent": 3.5},
        {"stock_name": "Mphasis", "weight_percent": 3.2},
        {"stock_name": "Coforge", "weight_percent": 3.0},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 2.8},
        {"stock_name": "Indian Hotels", "weight_percent": 2.6},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.4},
        {"stock_name": "Ipca Laboratories", "weight_percent": 2.2},
        {"stock_name": "Sundram Fasteners", "weight_percent": 2.0},
        {"stock_name": "Cummins India", "weight_percent": 1.9},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.8},
        {"stock_name": "KPIT Technologies", "weight_percent": 1.7},
        {"stock_name": "Tata Communications", "weight_percent": 1.6},
        {"stock_name": "Emami", "weight_percent": 1.5},
        {"stock_name": "Oracle Financial Services", "weight_percent": 1.4},
    ],
    "kotak emerging equity fund": [
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.1},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.7},
        {"stock_name": "Persistent Systems", "weight_percent": 3.4},
        {"stock_name": "Indian Hotels", "weight_percent": 3.1},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.7},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.5},
        {"stock_name": "Cummins India", "weight_percent": 2.3},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.1},
        {"stock_name": "Ipca Laboratories", "weight_percent": 1.9},
        {"stock_name": "Sundaram Finance", "weight_percent": 1.8},
        {"stock_name": "Tata Communications", "weight_percent": 1.7},
        {"stock_name": "Emami", "weight_percent": 1.6},
        {"stock_name": "Mphasis", "weight_percent": 1.5},
        {"stock_name": "Affle India", "weight_percent": 1.4},
    ],
    "axis midcap fund": [
        {"stock_name": "Persistent Systems", "weight_percent": 4.2},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 3.9},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.6},
        {"stock_name": "Indian Hotels", "weight_percent": 3.3},
        {"stock_name": "Coforge", "weight_percent": 3.1},
        {"stock_name": "Astral", "weight_percent": 2.8},
        {"stock_name": "Cummins India", "weight_percent": 2.6},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.4},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.2},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.0},
        {"stock_name": "Mphasis", "weight_percent": 1.9},
        {"stock_name": "Oracle Financial Services", "weight_percent": 1.8},
        {"stock_name": "Dixon Technologies", "weight_percent": 1.7},
        {"stock_name": "Tata Communications", "weight_percent": 1.6},
        {"stock_name": "Emami", "weight_percent": 1.5},
    ],
    "mirae asset emerging bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 6.8},
        {"stock_name": "ICICI Bank", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 4.7},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.2},
        {"stock_name": "Persistent Systems", "weight_percent": 3.8},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.5},
        {"stock_name": "Reliance Industries", "weight_percent": 3.2},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Infosys", "weight_percent": 2.7},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.5},
        {"stock_name": "Indian Hotels", "weight_percent": 2.3},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.1},
        {"stock_name": "Tata Motors", "weight_percent": 1.9},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.7},
        {"stock_name": "Cummins India", "weight_percent": 1.6},
    ],
    "nippon india growth fund": [
        {"stock_name": "KPIT Technologies", "weight_percent": 4.2},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 3.9},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.6},
        {"stock_name": "Persistent Systems", "weight_percent": 3.3},
        {"stock_name": "Indian Hotels", "weight_percent": 3.0},
        {"stock_name": "Coforge", "weight_percent": 2.8},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.6},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.4},
        {"stock_name": "Cummins India", "weight_percent": 2.2},
        {"stock_name": "Ipca Laboratories", "weight_percent": 2.0},
        {"stock_name": "Sundram Fasteners", "weight_percent": 1.9},
        {"stock_name": "Tata Communications", "weight_percent": 1.8},
        {"stock_name": "Emami", "weight_percent": 1.7},
        {"stock_name": "Mphasis", "weight_percent": 1.6},
        {"stock_name": "Dixon Technologies", "weight_percent": 1.5},
    ],
    "motilal oswal midcap fund": [
        {"stock_name": "Coforge", "weight_percent": 8.2},
        {"stock_name": "Persistent Systems", "weight_percent": 7.8},
        {"stock_name": "Kaynes Technology", "weight_percent": 6.5},
        {"stock_name": "Zomato", "weight_percent": 6.1},
        {"stock_name": "Dixon Technologies", "weight_percent": 5.7},
        {"stock_name": "Polycab India", "weight_percent": 5.2},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.8},
        {"stock_name": "BSE Ltd", "weight_percent": 4.4},
        {"stock_name": "Tube Investments of India", "weight_percent": 4.0},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.6},
        {"stock_name": "Indian Hotels", "weight_percent": 3.2},
        {"stock_name": "One 97 Communications (Paytm)", "weight_percent": 2.8},
        {"stock_name": "Affle India", "weight_percent": 2.5},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.2},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.9},
    ],
    "dsp flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 8.7},
        {"stock_name": "ICICI Bank", "weight_percent": 7.5},
        {"stock_name": "Infosys", "weight_percent": 6.8},
        {"stock_name": "Reliance Industries", "weight_percent": 6.1},
        {"stock_name": "Axis Bank", "weight_percent": 5.3},
        {"stock_name": "TCS", "weight_percent": 4.7},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.7},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.2},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.8},
        {"stock_name": "State Bank of India", "weight_percent": 2.5},
        {"stock_name": "ITC", "weight_percent": 2.2},
        {"stock_name": "HUL", "weight_percent": 2.0},
        {"stock_name": "Titan Company", "weight_percent": 1.8},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 1.6},
    ],
    "franklin india flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 8.4},
        {"stock_name": "ICICI Bank", "weight_percent": 7.6},
        {"stock_name": "Infosys", "weight_percent": 6.5},
        {"stock_name": "Reliance Industries", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 5.1},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.6},
        {"stock_name": "TCS", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "State Bank of India", "weight_percent": 3.4},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.0},
        {"stock_name": "HCL Technologies", "weight_percent": 2.7},
        {"stock_name": "ITC", "weight_percent": 2.4},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.9},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "jioblackrock flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 8.9},
        {"stock_name": "ICICI Bank", "weight_percent": 7.8},
        {"stock_name": "Reliance Industries", "weight_percent": 6.5},
        {"stock_name": "Infosys", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 5.2},
        {"stock_name": "TCS", "weight_percent": 4.7},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.4},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "State Bank of India", "weight_percent": 2.8},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.5},
        {"stock_name": "HCL Technologies", "weight_percent": 2.2},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.9},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 1.7},
    ],
    "axis large cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 9.06},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.22},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.04},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 4.78},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.74},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.77},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.53},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.41},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.12},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.06},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.98},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 2.84},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.77},
        {"stock_name": "Titan Co Ltd", "weight_percent": 2.43},
        {"stock_name": "State Bank of India", "weight_percent": 2.31},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.8},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 1.76},
        {"stock_name": "Pidilite Industries Ltd", "weight_percent": 1.62},
        {"stock_name": "NTPC Ltd", "weight_percent": 1.54},
    ],
    "quant flexi cap fund": [
        {"stock_name": "Reliance Industries", "weight_percent": 8.9},
        {"stock_name": "HDFC Bank", "weight_percent": 7.2},
        {"stock_name": "ICICI Bank", "weight_percent": 6.4},
        {"stock_name": "Jio Financial Services", "weight_percent": 5.8},
        {"stock_name": "ITC", "weight_percent": 5.2},
        {"stock_name": "Waaree Energies", "weight_percent": 4.6},
        {"stock_name": "IRB Infrastructure Developers", "weight_percent": 4.1},
        {"stock_name": "Samvardhana Motherson", "weight_percent": 3.7},
        {"stock_name": "ONGC", "weight_percent": 3.3},
        {"stock_name": "State Bank of India", "weight_percent": 2.9},
        {"stock_name": "Patanjali Foods", "weight_percent": 2.6},
        {"stock_name": "Bikaji Foods", "weight_percent": 2.3},
        {"stock_name": "GNFC", "weight_percent": 2.0},
        {"stock_name": "Inox Wind", "weight_percent": 1.8},
        {"stock_name": "SAIL", "weight_percent": 1.6},
    ],
}

# Aliases for common name variations
FUND_ALIASES = {
    "axis bluechip": "axis bluechip fund",
    "mirae asset large cap": "mirae asset large cap fund",
    "mirae large cap": "mirae asset large cap fund",
    "hdfc flexi cap": "hdfc flexi cap fund",
    "hdfc flexicap": "hdfc flexi cap fund",
    "hdfc top 100": "hdfc top 100 fund",
    "sbi bluechip": "sbi bluechip fund",
    "icici pru bluechip": "icici prudential bluechip fund",
    "icici prudential bluechip": "icici prudential bluechip fund",
    "parag parikh flexi cap": "parag parikh flexi cap fund",
    "ppfas flexi cap": "parag parikh flexi cap fund",
    "kotak flexi cap": "kotak flexicap fund",
    "kotak flexicap": "kotak flexicap fund",
    "jioblackrock flexi cap": "jioblackrock flexi cap fund",
    "jio blackrock flexi cap": "jioblackrock flexi cap fund",
    "nippon india growth mid cap": "nippon india growth fund",
    "nippon india mid cap": "nippon india growth fund",
    "nippon large cap": "nippon india large cap fund",
    "canara robeco bluechip": "canara robeco bluechip equity fund",
    "sbi small cap": "sbi small cap fund",
    "nippon small cap": "nippon india small cap fund",
    "axis small cap": "axis small cap fund",
    "bandhan small cap": "bandhan small cap fund",
    "quant small cap": "quant small cap fund",
    "hdfc mid cap": "hdfc mid-cap opportunities fund",
    "hdfc midcap": "hdfc mid-cap opportunities fund",
    "kotak emerging equity": "kotak emerging equity fund",
    "axis midcap": "axis midcap fund",
    "axis mid cap": "axis midcap fund",
    "mirae emerging bluechip": "mirae asset emerging bluechip fund",
    "mirae asset emerging": "mirae asset emerging bluechip fund",
    "motilal midcap": "motilal oswal midcap fund",
    "motilal oswal midcap": "motilal oswal midcap fund",
    "dsp flexi cap": "dsp flexi cap fund",
    "dsp flexicap": "dsp flexi cap fund",
    "franklin flexi cap": "franklin india flexi cap fund",
    "quant flexi cap": "quant flexi cap fund",
    "axis large cap": "axis large cap fund",
    "icici prudential large cap": "icici prudential bluechip fund",
    "icici pru large cap": "icici prudential bluechip fund",
}


def _clean_fund_name(fund_name: str) -> str:
    """Normalize fund name for matching."""
    import re
    name = fund_name.lower().strip()
    # Replace hyphens with spaces
    name = name.replace("-", " ")
    # Remove noise words/suffixes
    noise = [
        "non demat", "demat", "direct plan", "regular plan", "direct",
        "regular", "growth", "idcw", "dividend", "payout", "reinvestment",
        r"\(g\)", r"\(d\)", r"\(idcw\)", r"\(nr\)", r"\(non demat\)",
        r"\(demat\)", "plan", "option",
    ]
    for n in noise:
        name = re.sub(r"\b" + n + r"\b", " ", name)
    # Collapse whitespace
    name = re.sub(r"\s+", " ", name).strip()
    return name


def lookup_fund_holdings(fund_name: str):
    """Look up holdings from static DB using fuzzy matching. Returns (holdings, matched_name) or (None, None)."""
    from difflib import SequenceMatcher

    name = _clean_fund_name(fund_name)

    # Check aliases first (also clean alias keys)
    for alias, canonical in FUND_ALIASES.items():
        if alias in name or name in alias:
            return FUND_HOLDINGS[canonical], canonical

    # Try exact key match
    if name in FUND_HOLDINGS:
        return FUND_HOLDINGS[name], name

    # Fuzzy match against all keys
    best_score = 0.0
    best_key = None
    for key in FUND_HOLDINGS:
        clean_key = _clean_fund_name(key)
        score = SequenceMatcher(None, name, clean_key).ratio()
        if score > best_score:
            best_score = score
            best_key = key

    print(f"  Fund lookup '{name}' -> best='{best_key}' score={best_score:.2f}")
    if best_score >= 0.62:
        return FUND_HOLDINGS[best_key], best_key

    return None, None
