# Static holdings database for top Indian equity mutual funds
# Source: Publicly disclosed monthly portfolios (May 2026)
# Weights are approximate % to NAV for equity holdings only

FUND_HOLDINGS = {
    "axis bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.8},
        {"stock_name": "ICICI Bank", "weight_percent": 8.4},
        {"stock_name": "Infosys", "weight_percent": 7.2},
        {"stock_name": "Reliance Industries", "weight_percent": 6.5},
        {"stock_name": "Bajaj Finance", "weight_percent": 5.1},
        {"stock_name": "TCS", "weight_percent": 4.8},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 4.2},
        {"stock_name": "Axis Bank", "weight_percent": 3.9},
        {"stock_name": "Larsen & Toubro", "weight_percent": 3.6},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.3},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.8},
        {"stock_name": "Avenue Supermarts", "weight_percent": 2.5},
        {"stock_name": "Titan Company", "weight_percent": 2.3},
        {"stock_name": "Asian Paints", "weight_percent": 2.1},
        {"stock_name": "HUL", "weight_percent": 1.9},
    ],
    "mirae asset large cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 10.2},
        {"stock_name": "ICICI Bank", "weight_percent": 8.7},
        {"stock_name": "Reliance Industries", "weight_percent": 7.8},
        {"stock_name": "Infosys", "weight_percent": 6.9},
        {"stock_name": "TCS", "weight_percent": 5.4},
        {"stock_name": "Axis Bank", "weight_percent": 4.6},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.1},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "State Bank of India", "weight_percent": 3.2},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.9},
        {"stock_name": "HCL Technologies", "weight_percent": 2.6},
        {"stock_name": "ITC", "weight_percent": 2.4},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.9},
    ],
    "hdfc flexi cap fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 8.9},
        {"stock_name": "HDFC Bank", "weight_percent": 8.3},
        {"stock_name": "Axis Bank", "weight_percent": 5.7},
        {"stock_name": "Infosys", "weight_percent": 5.2},
        {"stock_name": "State Bank of India", "weight_percent": 4.8},
        {"stock_name": "Reliance Industries", "weight_percent": 4.5},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 4.1},
        {"stock_name": "Larsen & Toubro", "weight_percent": 3.9},
        {"stock_name": "Bajaj Finance", "weight_percent": 3.4},
        {"stock_name": "Maruti Suzuki", "weight_percent": 3.1},
        {"stock_name": "TCS", "weight_percent": 2.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 2.6},
        {"stock_name": "ITC", "weight_percent": 2.3},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Titan Company", "weight_percent": 1.8},
    ],
    "hdfc top 100 fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 10.1},
        {"stock_name": "HDFC Bank", "weight_percent": 9.4},
        {"stock_name": "Reliance Industries", "weight_percent": 7.2},
        {"stock_name": "Infosys", "weight_percent": 6.1},
        {"stock_name": "Axis Bank", "weight_percent": 5.5},
        {"stock_name": "State Bank of India", "weight_percent": 5.0},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.6},
        {"stock_name": "TCS", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.4},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.7},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.4},
        {"stock_name": "HCL Technologies", "weight_percent": 2.1},
        {"stock_name": "NTPC", "weight_percent": 1.9},
    ],
    "sbi bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.6},
        {"stock_name": "ICICI Bank", "weight_percent": 8.2},
        {"stock_name": "Reliance Industries", "weight_percent": 7.1},
        {"stock_name": "Infosys", "weight_percent": 6.3},
        {"stock_name": "Larsen & Toubro", "weight_percent": 5.2},
        {"stock_name": "Axis Bank", "weight_percent": 4.7},
        {"stock_name": "TCS", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.9},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "State Bank of India", "weight_percent": 3.2},
        {"stock_name": "HUL", "weight_percent": 2.8},
        {"stock_name": "ITC", "weight_percent": 2.5},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.2},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.0},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "icici prudential bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.9},
        {"stock_name": "ICICI Bank", "weight_percent": 8.6},
        {"stock_name": "Reliance Industries", "weight_percent": 7.4},
        {"stock_name": "Infosys", "weight_percent": 6.5},
        {"stock_name": "TCS", "weight_percent": 5.1},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.7},
        {"stock_name": "Axis Bank", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.9},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "State Bank of India", "weight_percent": 2.8},
        {"stock_name": "HUL", "weight_percent": 2.4},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.1},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.9},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 1.7},
    ],
    "parag parikh flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 7.8},
        {"stock_name": "Bajaj Holdings", "weight_percent": 6.2},
        {"stock_name": "ITC", "weight_percent": 5.9},
        {"stock_name": "Power Grid Corporation", "weight_percent": 5.3},
        {"stock_name": "Coal India", "weight_percent": 4.8},
        {"stock_name": "ICICI Bank", "weight_percent": 4.5},
        {"stock_name": "Axis Bank", "weight_percent": 4.1},
        {"stock_name": "HCL Technologies", "weight_percent": 3.7},
        {"stock_name": "Alphabet Inc (US)", "weight_percent": 3.4},
        {"stock_name": "Meta Platforms (US)", "weight_percent": 3.1},
        {"stock_name": "Microsoft (US)", "weight_percent": 2.8},
        {"stock_name": "Amazon (US)", "weight_percent": 2.5},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.2},
        {"stock_name": "CDSL", "weight_percent": 1.9},
        {"stock_name": "Zydus Lifesciences", "weight_percent": 1.7},
    ],
    "kotak flexicap fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 8.5},
        {"stock_name": "HDFC Bank", "weight_percent": 7.9},
        {"stock_name": "Infosys", "weight_percent": 6.8},
        {"stock_name": "Reliance Industries", "weight_percent": 6.2},
        {"stock_name": "Axis Bank", "weight_percent": 5.1},
        {"stock_name": "TCS", "weight_percent": 4.7},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.3},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bajaj Finance", "weight_percent": 3.4},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.1},
        {"stock_name": "State Bank of India", "weight_percent": 2.7},
        {"stock_name": "HUL", "weight_percent": 2.4},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Titan Company", "weight_percent": 1.8},
        {"stock_name": "ITC", "weight_percent": 1.6},
    ],
    "nippon india large cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.3},
        {"stock_name": "ICICI Bank", "weight_percent": 8.1},
        {"stock_name": "Reliance Industries", "weight_percent": 7.5},
        {"stock_name": "Infosys", "weight_percent": 6.4},
        {"stock_name": "State Bank of India", "weight_percent": 5.6},
        {"stock_name": "Larsen & Toubro", "weight_percent": 5.0},
        {"stock_name": "TCS", "weight_percent": 4.5},
        {"stock_name": "Axis Bank", "weight_percent": 4.0},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.5},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 2.8},
        {"stock_name": "NTPC", "weight_percent": 2.4},
        {"stock_name": "Power Grid Corporation", "weight_percent": 2.1},
        {"stock_name": "HCL Technologies", "weight_percent": 1.9},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "canara robeco bluechip equity fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 9.1},
        {"stock_name": "ICICI Bank", "weight_percent": 8.3},
        {"stock_name": "Infosys", "weight_percent": 7.0},
        {"stock_name": "Reliance Industries", "weight_percent": 6.4},
        {"stock_name": "TCS", "weight_percent": 5.5},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.8},
        {"stock_name": "Axis Bank", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.7},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.3},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.9},
        {"stock_name": "ITC", "weight_percent": 2.6},
        {"stock_name": "HUL", "weight_percent": 2.3},
        {"stock_name": "State Bank of India", "weight_percent": 2.0},
        {"stock_name": "HCL Technologies", "weight_percent": 1.8},
        {"stock_name": "Asian Paints", "weight_percent": 1.6},
    ],
    "sbi small cap fund": [
        {"stock_name": "Nuvoco Vistas", "weight_percent": 3.8},
        {"stock_name": "Welspun Living", "weight_percent": 3.5},
        {"stock_name": "Blue Star", "weight_percent": 3.2},
        {"stock_name": "Chalet Hotels", "weight_percent": 2.9},
        {"stock_name": "Hawkins Cookers", "weight_percent": 2.7},
        {"stock_name": "Greenpanel Industries", "weight_percent": 2.5},
        {"stock_name": "Shaily Engineering Plastics", "weight_percent": 2.3},
        {"stock_name": "Suprajit Engineering", "weight_percent": 2.1},
        {"stock_name": "V-Guard Industries", "weight_percent": 2.0},
        {"stock_name": "Dodla Dairy", "weight_percent": 1.9},
        {"stock_name": "Mold-Tek Packaging", "weight_percent": 1.8},
        {"stock_name": "Repco Home Finance", "weight_percent": 1.7},
        {"stock_name": "Srikalahasthi Pipes", "weight_percent": 1.6},
        {"stock_name": "Marksans Pharma", "weight_percent": 1.5},
        {"stock_name": "Safari Industries", "weight_percent": 1.4},
    ],
    "nippon india small cap fund": [
        {"stock_name": "KPIT Technologies", "weight_percent": 3.1},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.8},
        {"stock_name": "Dixon Technologies", "weight_percent": 2.6},
        {"stock_name": "Affle India", "weight_percent": 2.4},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.2},
        {"stock_name": "Kaynes Technology", "weight_percent": 2.1},
        {"stock_name": "Cams Services", "weight_percent": 1.9},
        {"stock_name": "Suven Pharmaceuticals", "weight_percent": 1.8},
        {"stock_name": "Caplin Point Laboratories", "weight_percent": 1.7},
        {"stock_name": "Techno Electric & Engineering", "weight_percent": 1.6},
        {"stock_name": "Tata Chemicals", "weight_percent": 1.5},
        {"stock_name": "PNB Housing Finance", "weight_percent": 1.4},
        {"stock_name": "Vinati Organics", "weight_percent": 1.4},
        {"stock_name": "Garware Technical Fibres", "weight_percent": 1.3},
        {"stock_name": "Aarti Industries", "weight_percent": 1.2},
    ],
    "axis small cap fund": [
        {"stock_name": "Kaynes Technology", "weight_percent": 3.4},
        {"stock_name": "Cholamandalam Financial Holdings", "weight_percent": 3.1},
        {"stock_name": "Affle India", "weight_percent": 2.9},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.7},
        {"stock_name": "Dixon Technologies", "weight_percent": 2.5},
        {"stock_name": "Suven Pharmaceuticals", "weight_percent": 2.3},
        {"stock_name": "Techno Electric & Engineering", "weight_percent": 2.1},
        {"stock_name": "Caplin Point Laboratories", "weight_percent": 2.0},
        {"stock_name": "Garware Technical Fibres", "weight_percent": 1.8},
        {"stock_name": "Vinati Organics", "weight_percent": 1.7},
        {"stock_name": "Safari Industries", "weight_percent": 1.6},
        {"stock_name": "Tube Investments of India", "weight_percent": 1.5},
        {"stock_name": "V-Guard Industries", "weight_percent": 1.4},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.3},
        {"stock_name": "Dodla Dairy", "weight_percent": 1.2},
    ],
    "bandhan small cap fund": [
        {"stock_name": "Nucleus Software Exports", "weight_percent": 3.2},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.9},
        {"stock_name": "Suven Pharmaceuticals", "weight_percent": 2.7},
        {"stock_name": "Dodla Dairy", "weight_percent": 2.5},
        {"stock_name": "Caplin Point Laboratories", "weight_percent": 2.3},
        {"stock_name": "Safari Industries", "weight_percent": 2.1},
        {"stock_name": "V-Guard Industries", "weight_percent": 1.9},
        {"stock_name": "Repco Home Finance", "weight_percent": 1.8},
        {"stock_name": "Craftsman Automation", "weight_percent": 1.7},
        {"stock_name": "Brigade Enterprises", "weight_percent": 1.6},
        {"stock_name": "HDFC Bank", "weight_percent": 0.55},
        {"stock_name": "Mold-Tek Packaging", "weight_percent": 1.5},
        {"stock_name": "Chalet Hotels", "weight_percent": 1.4},
        {"stock_name": "Marksans Pharma", "weight_percent": 1.3},
        {"stock_name": "Techno Electric & Engineering", "weight_percent": 1.2},
    ],
    "quant small cap fund": [
        {"stock_name": "Reliance Industries", "weight_percent": 5.2},
        {"stock_name": "IRB Infrastructure Developers", "weight_percent": 3.8},
        {"stock_name": "Waaree Energies", "weight_percent": 3.5},
        {"stock_name": "Jio Financial Services", "weight_percent": 3.2},
        {"stock_name": "Bikaji Foods", "weight_percent": 2.9},
        {"stock_name": "Patanjali Foods", "weight_percent": 2.7},
        {"stock_name": "GNFC", "weight_percent": 2.5},
        {"stock_name": "Aarti Industries", "weight_percent": 2.3},
        {"stock_name": "RBL Bank", "weight_percent": 2.1},
        {"stock_name": "Inox Wind", "weight_percent": 2.0},
        {"stock_name": "SAIL", "weight_percent": 1.8},
        {"stock_name": "Manappuram Finance", "weight_percent": 1.7},
        {"stock_name": "Tata Teleservices", "weight_percent": 1.5},
        {"stock_name": "Trident", "weight_percent": 1.4},
        {"stock_name": "Strides Pharma", "weight_percent": 1.3},
    ],
    "hdfc mid-cap opportunities fund": [
        {"stock_name": "Cholamandalam Investment", "weight_percent": 3.8},
        {"stock_name": "Persistent Systems", "weight_percent": 3.5},
        {"stock_name": "Mphasis", "weight_percent": 3.2},
        {"stock_name": "Coforge", "weight_percent": 3.0},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 2.8},
        {"stock_name": "Indian Hotels", "weight_percent": 2.6},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.4},
        {"stock_name": "Ipca Laboratories", "weight_percent": 2.2},
        {"stock_name": "Sundram Fasteners", "weight_percent": 2.0},
        {"stock_name": "Cummins India", "weight_percent": 1.9},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.8},
        {"stock_name": "KPIT Technologies", "weight_percent": 1.7},
        {"stock_name": "Tata Communications", "weight_percent": 1.6},
        {"stock_name": "Emami", "weight_percent": 1.5},
        {"stock_name": "Oracle Financial Services", "weight_percent": 1.4},
    ],
    "kotak emerging equity fund": [
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.1},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.7},
        {"stock_name": "Persistent Systems", "weight_percent": 3.4},
        {"stock_name": "Indian Hotels", "weight_percent": 3.1},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.7},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.5},
        {"stock_name": "Cummins India", "weight_percent": 2.3},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.1},
        {"stock_name": "Ipca Laboratories", "weight_percent": 1.9},
        {"stock_name": "Sundaram Finance", "weight_percent": 1.8},
        {"stock_name": "Tata Communications", "weight_percent": 1.7},
        {"stock_name": "Emami", "weight_percent": 1.6},
        {"stock_name": "Mphasis", "weight_percent": 1.5},
        {"stock_name": "Affle India", "weight_percent": 1.4},
    ],
    "axis midcap fund": [
        {"stock_name": "Persistent Systems", "weight_percent": 4.2},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 3.9},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.6},
        {"stock_name": "Indian Hotels", "weight_percent": 3.3},
        {"stock_name": "Coforge", "weight_percent": 3.1},
        {"stock_name": "Astral", "weight_percent": 2.8},
        {"stock_name": "Cummins India", "weight_percent": 2.6},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.4},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.2},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.0},
        {"stock_name": "Mphasis", "weight_percent": 1.9},
        {"stock_name": "Oracle Financial Services", "weight_percent": 1.8},
        {"stock_name": "Dixon Technologies", "weight_percent": 1.7},
        {"stock_name": "Tata Communications", "weight_percent": 1.6},
        {"stock_name": "Emami", "weight_percent": 1.5},
    ],
    "mirae asset emerging bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 6.8},
        {"stock_name": "ICICI Bank", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 4.7},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.2},
        {"stock_name": "Persistent Systems", "weight_percent": 3.8},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.5},
        {"stock_name": "Reliance Industries", "weight_percent": 3.2},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Infosys", "weight_percent": 2.7},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.5},
        {"stock_name": "Indian Hotels", "weight_percent": 2.3},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.1},
        {"stock_name": "Tata Motors", "weight_percent": 1.9},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.7},
        {"stock_name": "Cummins India", "weight_percent": 1.6},
    ],
    "motilal oswal midcap fund": [
        {"stock_name": "Coforge", "weight_percent": 8.2},
        {"stock_name": "Persistent Systems", "weight_percent": 7.8},
        {"stock_name": "Kaynes Technology", "weight_percent": 6.5},
        {"stock_name": "Zomato", "weight_percent": 6.1},
        {"stock_name": "Dixon Technologies", "weight_percent": 5.7},
        {"stock_name": "Polycab India", "weight_percent": 5.2},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.8},
        {"stock_name": "BSE Ltd", "weight_percent": 4.4},
        {"stock_name": "Tube Investments of India", "weight_percent": 4.0},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.6},
        {"stock_name": "Indian Hotels", "weight_percent": 3.2},
        {"stock_name": "One 97 Communications (Paytm)", "weight_percent": 2.8},
        {"stock_name": "Affle India", "weight_percent": 2.5},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.2},
        {"stock_name": "Bharat Electronics", "weight_percent": 1.9},
    ],
    "dsp flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 8.7},
        {"stock_name": "ICICI Bank", "weight_percent": 7.5},
        {"stock_name": "Infosys", "weight_percent": 6.8},
        {"stock_name": "Reliance Industries", "weight_percent": 6.1},
        {"stock_name": "Axis Bank", "weight_percent": 5.3},
        {"stock_name": "TCS", "weight_percent": 4.7},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.7},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.2},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.8},
        {"stock_name": "State Bank of India", "weight_percent": 2.5},
        {"stock_name": "ITC", "weight_percent": 2.2},
        {"stock_name": "HUL", "weight_percent": 2.0},
        {"stock_name": "Titan Company", "weight_percent": 1.8},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 1.6},
    ],
    "franklin india flexi cap fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 8.4},
        {"stock_name": "ICICI Bank", "weight_percent": 7.6},
        {"stock_name": "Infosys", "weight_percent": 6.5},
        {"stock_name": "Reliance Industries", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 5.1},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.6},
        {"stock_name": "TCS", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "State Bank of India", "weight_percent": 3.4},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.0},
        {"stock_name": "HCL Technologies", "weight_percent": 2.7},
        {"stock_name": "ITC", "weight_percent": 2.4},
        {"stock_name": "Sun Pharmaceutical", "weight_percent": 2.1},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.9},
        {"stock_name": "Maruti Suzuki", "weight_percent": 1.7},
    ],
    "quant flexi cap fund": [
        {"stock_name": "Reliance Industries", "weight_percent": 8.9},
        {"stock_name": "HDFC Bank", "weight_percent": 7.2},
        {"stock_name": "ICICI Bank", "weight_percent": 6.4},
        {"stock_name": "Jio Financial Services", "weight_percent": 5.8},
        {"stock_name": "ITC", "weight_percent": 5.2},
        {"stock_name": "Waaree Energies", "weight_percent": 4.6},
        {"stock_name": "IRB Infrastructure Developers", "weight_percent": 4.1},
        {"stock_name": "Samvardhana Motherson", "weight_percent": 3.7},
        {"stock_name": "ONGC", "weight_percent": 3.3},
        {"stock_name": "State Bank of India", "weight_percent": 2.9},
        {"stock_name": "Patanjali Foods", "weight_percent": 2.6},
        {"stock_name": "Bikaji Foods", "weight_percent": 2.3},
        {"stock_name": "GNFC", "weight_percent": 2.0},
        {"stock_name": "Inox Wind", "weight_percent": 1.8},
        {"stock_name": "SAIL", "weight_percent": 1.6},
    ],
}

# Aliases for common name variations
FUND_ALIASES = {
    "axis bluechip": "axis bluechip fund",
    "mirae asset large cap": "mirae asset large cap fund",
    "mirae large cap": "mirae asset large cap fund",
    "hdfc flexi cap": "hdfc flexi cap fund",
    "hdfc flexicap": "hdfc flexi cap fund",
    "hdfc top 100": "hdfc top 100 fund",
    "sbi bluechip": "sbi bluechip fund",
    "icici pru bluechip": "icici prudential bluechip fund",
    "icici prudential bluechip": "icici prudential bluechip fund",
    "parag parikh flexi cap": "parag parikh flexi cap fund",
    "ppfas flexi cap": "parag parikh flexi cap fund",
    "kotak flexi cap": "kotak flexicap fund",
    "kotak flexicap": "kotak flexicap fund",
    "nippon large cap": "nippon india large cap fund",
    "canara robeco bluechip": "canara robeco bluechip equity fund",
    "sbi small cap": "sbi small cap fund",
    "nippon small cap": "nippon india small cap fund",
    "axis small cap": "axis small cap fund",
    "bandhan small cap": "bandhan small cap fund",
    "quant small cap": "quant small cap fund",
    "hdfc mid cap": "hdfc mid-cap opportunities fund",
    "hdfc midcap": "hdfc mid-cap opportunities fund",
    "kotak emerging equity": "kotak emerging equity fund",
    "axis midcap": "axis midcap fund",
    "axis mid cap": "axis midcap fund",
    "mirae emerging bluechip": "mirae asset emerging bluechip fund",
    "mirae asset emerging": "mirae asset emerging bluechip fund",
    "motilal midcap": "motilal oswal midcap fund",
    "motilal oswal midcap": "motilal oswal midcap fund",
    "dsp flexi cap": "dsp flexi cap fund",
    "dsp flexicap": "dsp flexi cap fund",
    "franklin flexi cap": "franklin india flexi cap fund",
    "quant flexi cap": "quant flexi cap fund",
}


def _clean_fund_name(fund_name: str) -> str:
    """Normalize fund name for matching."""
    import re
    name = fund_name.lower().strip()
    # Replace hyphens with spaces
    name = name.replace("-", " ")
    # Remove noise words/suffixes
    noise = [
        "non demat", "demat", "direct plan", "regular plan", "direct",
        "regular", "growth", "idcw", "dividend", "payout", "reinvestment",
        r"\(g\)", r"\(d\)", r"\(idcw\)", r"\(nr\)", r"\(non demat\)",
        r"\(demat\)", "plan", "option",
    ]
    for n in noise:
        name = re.sub(r"\b" + n + r"\b", " ", name)
    # Collapse whitespace
    name = re.sub(r"\s+", " ", name).strip()
    return name


def lookup_fund_holdings(fund_name: str):
    """Look up holdings from static DB using fuzzy matching. Returns (holdings, matched_name) or (None, None)."""
    from difflib import SequenceMatcher

    name = _clean_fund_name(fund_name)

    # Check aliases first (also clean alias keys)
    for alias, canonical in FUND_ALIASES.items():
        if alias in name or name in alias:
            return FUND_HOLDINGS[canonical], canonical

    # Try exact key match
    if name in FUND_HOLDINGS:
        return FUND_HOLDINGS[name], name

    # Fuzzy match against all keys
    best_score = 0.0
    best_key = None
    for key in FUND_HOLDINGS:
        clean_key = _clean_fund_name(key)
        score = SequenceMatcher(None, name, clean_key).ratio()
        if score > best_score:
            best_score = score
            best_key = key

    print(f"  Fund lookup '{name}' -> best='{best_key}' score={best_score:.2f}")
    if best_score >= 0.62:
        return FUND_HOLDINGS[best_key], best_key

    return None, None
