# Static holdings database for top Indian equity mutual funds
# Source: Publicly disclosed monthly portfolios (May 2026)
# Weights are approximate % to NAV for equity holdings only

FUND_HOLDINGS = {
    "axis bluechip fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 9.06},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.22},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.04},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 4.78},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.74},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.77},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.53},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.41},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.12},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.06},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.98},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 2.84},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.77},
        {"stock_name": "Titan Co Ltd", "weight_percent": 2.43},
        {"stock_name": "State Bank of India", "weight_percent": 2.31},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.8},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 1.76},
        {"stock_name": "Pidilite Industries Ltd", "weight_percent": 1.62},
        {"stock_name": "NTPC Ltd", "weight_percent": 1.54},
    ],
    "mirae asset large cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.96},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.19},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.4},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 5.32},
        {"stock_name": "Infosys Ltd", "weight_percent": 4.08},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.57},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.46},
        {"stock_name": "State Bank of India", "weight_percent": 2.93},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.55},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.43},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.43},
        {"stock_name": "ITC Ltd", "weight_percent": 2.42},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 2.09},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.79},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.7},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 1.61},
        {"stock_name": "Britannia Industries Ltd", "weight_percent": 1.45},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 1.39},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 1.35},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.32},
    ],
    "hdfc flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.83},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 6.84},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 6.48},
        {"stock_name": "State Bank of India", "weight_percent": 4.22},
        {"stock_name": "SBI Life Insurance Co Ltd", "weight_percent": 3.76},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.55},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.43},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.96},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.91},
        {"stock_name": "Cipla Ltd", "weight_percent": 2.89},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 2.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.73},
        {"stock_name": "Power Grid Corp Of India Ltd", "weight_percent": 2.51},
        {"stock_name": "HCL Technologies Ltd", "weight_percent": 2.47},
        {"stock_name": "Eicher Motors Ltd", "weight_percent": 2.46},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 2.01},
        {"stock_name": "Bajaj Auto Ltd", "weight_percent": 1.78},
        {"stock_name": "JSW Steel Ltd", "weight_percent": 1.72},
        {"stock_name": "Hyundai Motor India Ltd", "weight_percent": 1.7},
        {"stock_name": "Piramal Pharma Ltd", "weight_percent": 1.53},
    ],
    "hdfc top 100 fund": [
        {"stock_name": "ICICI Bank", "weight_percent": 10.1},
        {"stock_name": "HDFC Bank", "weight_percent": 9.4},
        {"stock_name": "Reliance Industries", "weight_percent": 7.2},
        {"stock_name": "Infosys", "weight_percent": 6.1},
        {"stock_name": "Axis Bank", "weight_percent": 5.5},
        {"stock_name": "State Bank of India", "weight_percent": 5.0},
        {"stock_name": "Larsen & Toubro", "weight_percent": 4.6},
        {"stock_name": "TCS", "weight_percent": 4.2},
        {"stock_name": "Kotak Mahindra Bank", "weight_percent": 3.8},
        {"stock_name": "Bharti Airtel", "weight_percent": 3.4},
        {"stock_name": "ITC", "weight_percent": 3.1},
        {"stock_name": "Maruti Suzuki", "weight_percent": 2.7},
        {"stock_name": "Bajaj Finance", "weight_percent": 2.4},
        {"stock_name": "HCL Technologies", "weight_percent": 2.1},
        {"stock_name": "NTPC", "weight_percent": 1.9},
    ],
    "sbi bluechip fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.42},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 7.71},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 6.05},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.64},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 4.14},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.86},
        {"stock_name": "State Bank of India", "weight_percent": 3.44},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 3.31},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.3},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 3.22},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 2.8},
        {"stock_name": "Thermax Ltd", "weight_percent": 2.7},
        {"stock_name": "Tata Motors Ltd", "weight_percent": 2.69},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 2.53},
        {"stock_name": "Varun Beverages Ltd", "weight_percent": 2.42},
        {"stock_name": "Avenue Supermarts Ltd", "weight_percent": 2.33},
        {"stock_name": "Page Industries Ltd", "weight_percent": 2.26},
        {"stock_name": "Shree Cement Ltd", "weight_percent": 2.24},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.19},
        {"stock_name": "Cholamandalam Investment and Finance Co Ltd", "weight_percent": 1.9},
    ],
    "icici prudential bluechip fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.72},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.46},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.41},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.38},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 4.67},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.34},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.6},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 3.55},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.69},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.65},
        {"stock_name": "NTPC Ltd", "weight_percent": 2.38},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.34},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 2.02},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 1.83},
        {"stock_name": "Hero MotoCorp Ltd", "weight_percent": 1.59},
        {"stock_name": "DLF Ltd", "weight_percent": 1.32},
        {"stock_name": "Oil & Natural Gas Corp Ltd", "weight_percent": 1.25},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.21},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 1.16},
        {"stock_name": "Hindustan Aeronautics Ltd Ordinary Shares", "weight_percent": 1.11},
    ],
    "parag parikh flexi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.88},
        {"stock_name": "Power Grid Corp Of India Ltd", "weight_percent": 6.41},
        {"stock_name": "ITC Ltd", "weight_percent": 5.84},
        {"stock_name": "Coal India Ltd", "weight_percent": 5.66},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.11},
        {"stock_name": "Alphabet Inc", "weight_percent": 4.83},
        {"stock_name": "Bajaj Holdings & Investment Ltd", "weight_percent": 4.48},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 4.12},
        {"stock_name": "HCL Technologies Ltd", "weight_percent": 3.6},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.45},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.06},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.02},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.82},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.74},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 2.54},
        {"stock_name": "Amazon.com Inc", "weight_percent": 2.51},
        {"stock_name": "Meta Platforms Inc", "weight_percent": 2.51},
        {"stock_name": "Microsoft Corp", "weight_percent": 2.22},
        {"stock_name": "Zydus Lifesciences Ltd", "weight_percent": 1.47},
        {"stock_name": "Cipla Ltd", "weight_percent": 1.39},
    ],
    "kotak flexicap fund": [
        {"stock_name": "Bharat Electronics Ltd", "weight_percent": 5.51},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 5.37},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.04},
        {"stock_name": "State Bank of India", "weight_percent": 4.19},
        {"stock_name": "Jindal Steel Ltd", "weight_percent": 4.19},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.94},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.76},
        {"stock_name": "Solar Industries India Ltd", "weight_percent": 3.33},
        {"stock_name": "Eternal Ltd", "weight_percent": 3.20},
        {"stock_name": "SRF Ltd", "weight_percent": 3.10},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.90},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.88},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 2.41},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 2.36},
        {"stock_name": "BSE Ltd", "weight_percent": 2.35},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 2.17},
        {"stock_name": "Zydus Lifesciences Ltd", "weight_percent": 2.06},
        {"stock_name": "Thermax Ltd", "weight_percent": 1.98},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 1.92},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 1.82},
    ],
    "nippon india large cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 9.31},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.19},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 4.2},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 4.06},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.52},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.47},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 2.81},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.8},
        {"stock_name": "Infosys Ltd", "weight_percent": 2.72},
        {"stock_name": "Hindustan Unilever Ltd", "weight_percent": 2.71},
        {"stock_name": "ITC Ltd", "weight_percent": 2.5},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.44},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.35},
        {"stock_name": "State Bank of India", "weight_percent": 2.35},
        {"stock_name": "Avenue Supermarts Ltd", "weight_percent": 2.2},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 2.19},
        {"stock_name": "NTPC Ltd", "weight_percent": 2.1},
        {"stock_name": "Tata Power Co Ltd", "weight_percent": 1.83},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 1.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 1.55},
    ],
    "canara robeco bluechip equity fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.14},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 7.77},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.18},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.67},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 4.35},
        {"stock_name": "State Bank of India", "weight_percent": 4.11},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.76},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.46},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.03},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 2.94},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.46},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 2.26},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.2},
        {"stock_name": "Varun Beverages Ltd", "weight_percent": 1.63},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.63},
        {"stock_name": "Tech Mahindra Ltd", "weight_percent": 1.53},
        {"stock_name": "Tata Steel Ltd", "weight_percent": 1.51},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.41},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 1.4},
        {"stock_name": "Tata Consumer Products Ltd", "weight_percent": 1.39},
    ],
    "sbi small cap fund": [
        {"stock_name": "Ather Energy Ltd", "weight_percent": 5.18},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 3.11},
        {"stock_name": "Honeywell Automation India Ltd", "weight_percent": 2.83},
        {"stock_name": "Kalpataru Projects International Ltd", "weight_percent": 2.76},
        {"stock_name": "ZF Commercial Vehicle Control Systems India Ltd", "weight_percent": 2.75},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 2.69},
        {"stock_name": "Belrise Industries Ltd", "weight_percent": 2.52},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.5},
        {"stock_name": "Sundaram Fasteners Ltd", "weight_percent": 2.3},
        {"stock_name": "SBFC Finance Ltd", "weight_percent": 2.25},
        {"stock_name": "Kajaria Ceramics Ltd", "weight_percent": 2.01},
        {"stock_name": "K.P.R. Mill Ltd", "weight_percent": 1.99},
        {"stock_name": "Deepak Fertilisers & Petrochemicals Corp Ltd", "weight_percent": 1.98},
        {"stock_name": "Anand Rathi Wealth Ltd", "weight_percent": 1.94},
        {"stock_name": "DOMS Industries Ltd", "weight_percent": 1.93},
        {"stock_name": "Chalet Hotels Ltd", "weight_percent": 1.89},
        {"stock_name": "E I D Parry India Ltd", "weight_percent": 1.88},
        {"stock_name": "Urban Co Ltd", "weight_percent": 1.72},
        {"stock_name": "Finolex Industries Ltd", "weight_percent": 1.72},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.66},
    ],
    "nippon india small cap fund": [
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.93},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 1.77},
        {"stock_name": "TD Power Systems Ltd", "weight_percent": 1.71},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.57},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 1.55},
        {"stock_name": "State Bank of India", "weight_percent": 1.29},
        {"stock_name": "NLC India Ltd", "weight_percent": 1.26},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 1.23},
        {"stock_name": "Zydus Wellness Ltd", "weight_percent": 1.17},
        {"stock_name": "Tube Investments of India Ltd", "weight_percent": 1.05},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.03},
        {"stock_name": "Kirloskar Brothers Ltd", "weight_percent": 0.99},
        {"stock_name": "MTAR Technologies Ltd", "weight_percent": 0.98},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 0.96},
        {"stock_name": "Sundaram Fasteners Ltd", "weight_percent": 0.95},
        {"stock_name": "Sai Life Sciences Ltd", "weight_percent": 0.91},
        {"stock_name": "Emami Ltd", "weight_percent": 0.9},
        {"stock_name": "Whirlpool of India Ltd", "weight_percent": 0.88},
        {"stock_name": "Kirloskar Pneumatic Co Ltd", "weight_percent": 0.87},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 0.86},
    ],
    "axis small cap fund": [
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.76},
        {"stock_name": "CCL Products (India) Ltd", "weight_percent": 2.55},
        {"stock_name": "J.B. Chemicals & Pharmaceuticals Ltd", "weight_percent": 2.32},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.89},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 1.81},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.57},
        {"stock_name": "Sai Life Sciences Ltd", "weight_percent": 1.57},
        {"stock_name": "Craftsman Automation Ltd", "weight_percent": 1.46},
        {"stock_name": "Brigade Enterprises Ltd", "weight_percent": 1.44},
        {"stock_name": "Blue Star Ltd", "weight_percent": 1.41},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 1.34},
        {"stock_name": "Minda Corp Ltd", "weight_percent": 1.29},
        {"stock_name": "Can Fin Homes Ltd", "weight_percent": 1.27},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 1.26},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 1.19},
        {"stock_name": "Vesuvius India Ltd", "weight_percent": 1.16},
        {"stock_name": "Narayana Hrudayalaya Ltd", "weight_percent": 1.13},
        {"stock_name": "Avalon Technologies Ltd", "weight_percent": 1.1},
        {"stock_name": "PB Fintech Ltd", "weight_percent": 1.09},
        {"stock_name": "Phoenix Mills Ltd", "weight_percent": 1.07},
    ],
    "bandhan small cap fund": [
        {"stock_name": "Sobha Ltd", "weight_percent": 3.18},
        {"stock_name": "REC Ltd", "weight_percent": 3.1},
        {"stock_name": "State Bank of India", "weight_percent": 2.02},
        {"stock_name": "LT Foods Ltd", "weight_percent": 1.88},
        {"stock_name": "Arvind Ltd", "weight_percent": 1.72},
        {"stock_name": "South Indian Bank Ltd", "weight_percent": 1.66},
        {"stock_name": "PNB Housing Finance Ltd", "weight_percent": 1.53},
        {"stock_name": "Jubilant Pharmova Ltd", "weight_percent": 1.31},
        {"stock_name": "Karnataka Bank Ltd", "weight_percent": 1.23},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.21},
        {"stock_name": "Paradeep Phosphates Ltd", "weight_percent": 1.21},
        {"stock_name": "Yatharth Hospital & Trauma Care Services Ltd", "weight_percent": 1.19},
        {"stock_name": "Cyient Ltd", "weight_percent": 1.17},
        {"stock_name": "Shaily Engineering Plastics Ltd", "weight_percent": 1.17},
        {"stock_name": "One97 Communications Ltd", "weight_percent": 1.13},
        {"stock_name": "Great Eastern Shipping Co Ltd", "weight_percent": 1.03},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 0.98},
        {"stock_name": "ICICI Lombard General Insurance Co Ltd", "weight_percent": 0.96},
        {"stock_name": "Sky Gold Ltd", "weight_percent": 0.96},
        {"stock_name": "Rashi Peripherals Ltd", "weight_percent": 0.94},
    ],
    "quant small cap fund": [
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 8.36},
        {"stock_name": "HFCL Ltd", "weight_percent": 5.1},
        {"stock_name": "RBL Bank Ltd", "weight_percent": 4.66},
        {"stock_name": "Adani Power Ltd", "weight_percent": 4.59},
        {"stock_name": "Adani Green Energy Ltd", "weight_percent": 3.23},
        {"stock_name": "Adani Enterprises Ltd", "weight_percent": 2.8},
        {"stock_name": "Piramal Finance Ltd", "weight_percent": 2.63},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 2.59},
        {"stock_name": "Anand Rathi Wealth Ltd", "weight_percent": 2.58},
        {"stock_name": "Sun TV Network Ltd", "weight_percent": 2.32},
        {"stock_name": "Arvind Ltd", "weight_percent": 2.21},
        {"stock_name": "Capri Global Capital Ltd", "weight_percent": 1.96},
        {"stock_name": "Viyash Scientific Ltd", "weight_percent": 1.92},
        {"stock_name": "Aegis Logistics Ltd", "weight_percent": 1.88},
        {"stock_name": "Welspun Corp Ltd", "weight_percent": 1.87},
        {"stock_name": "Poly Medicure Ltd", "weight_percent": 1.85},
        {"stock_name": "Bikaji Foods International Ltd", "weight_percent": 1.77},
        {"stock_name": "Usha Martin Ltd", "weight_percent": 1.71},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 1.69},
        {"stock_name": "Ventive Hospitality Ltd", "weight_percent": 1.65},
    ],
    "hdfc mid-cap opportunities fund": [
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 4.49},
        {"stock_name": "AU Small Finance Bank Ltd", "weight_percent": 4.01},
        {"stock_name": "Federal Bank Ltd", "weight_percent": 3.79},
        {"stock_name": "Balkrishna Industries Ltd", "weight_percent": 3.25},
        {"stock_name": "Indian Bank", "weight_percent": 3.15},
        {"stock_name": "Glenmark Pharmaceuticals Ltd", "weight_percent": 3.13},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 3.09},
        {"stock_name": "Ipca Laboratories Ltd", "weight_percent": 2.83},
        {"stock_name": "Vishal Mega Mart Ltd", "weight_percent": 2.83},
        {"stock_name": "Cummins India Ltd", "weight_percent": 2.72},
        {"stock_name": "Marico Ltd", "weight_percent": 2.55},
        {"stock_name": "Coforge Ltd", "weight_percent": 2.28},
        {"stock_name": "Tata Communications Ltd", "weight_percent": 2.25},
        {"stock_name": "Hindustan Petroleum Corp Ltd", "weight_percent": 2.25},
        {"stock_name": "Mahindra & Mahindra Financial Services Ltd", "weight_percent": 1.99},
        {"stock_name": "Aurobindo Pharma Ltd", "weight_percent": 1.96},
        {"stock_name": "Jindal Steel & Power Ltd", "weight_percent": 1.82},
        {"stock_name": "Persistent Systems Ltd", "weight_percent": 1.79},
        {"stock_name": "Alkem Laboratories Ltd", "weight_percent": 1.79},
        {"stock_name": "Apollo Tyres Ltd", "weight_percent": 1.7},
    ],
    "kotak emerging equity fund": [
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.1},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.7},
        {"stock_name": "Persistent Systems", "weight_percent": 3.4},
        {"stock_name": "Indian Hotels", "weight_percent": 3.1},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.7},
        {"stock_name": "Tube Investments of India", "weight_percent": 2.5},
        {"stock_name": "Cummins India", "weight_percent": 2.3},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.1},
        {"stock_name": "Ipca Laboratories", "weight_percent": 1.9},
        {"stock_name": "Sundaram Finance", "weight_percent": 1.8},
        {"stock_name": "Tata Communications", "weight_percent": 1.7},
        {"stock_name": "Emami", "weight_percent": 1.6},
        {"stock_name": "Mphasis", "weight_percent": 1.5},
        {"stock_name": "Affle India", "weight_percent": 1.4},
    ],
    "axis midcap fund": [
        {"stock_name": "The Federal Bank Ltd", "weight_percent": 3.83},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 3.54},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 3.04},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 2.90},
        {"stock_name": "BSE Ltd", "weight_percent": 2.39},
        {"stock_name": "Schaeffler India Ltd", "weight_percent": 2.22},
        {"stock_name": "Cummins India Ltd", "weight_percent": 2.11},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 2.09},
        {"stock_name": "Solar Industries India Ltd", "weight_percent": 2.07},
        {"stock_name": "Indian Hotels Co Ltd", "weight_percent": 2.06},
        {"stock_name": "Hitachi Energy India Ltd", "weight_percent": 1.94},
        {"stock_name": "Phoenix Mills Ltd", "weight_percent": 1.93},
        {"stock_name": "Sona BLW Precision Forgings Ltd", "weight_percent": 1.89},
        {"stock_name": "Ipca Laboratories Ltd", "weight_percent": 1.86},
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.84},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 1.77},
        {"stock_name": "Premier Energies Ltd", "weight_percent": 1.67},
        {"stock_name": "Coromandel International Ltd", "weight_percent": 1.59},
        {"stock_name": "PB Fintech Ltd", "weight_percent": 1.59},
        {"stock_name": "UNO Minda Ltd", "weight_percent": 1.44},
    ],
    "mirae asset emerging bluechip fund": [
        {"stock_name": "HDFC Bank", "weight_percent": 6.8},
        {"stock_name": "ICICI Bank", "weight_percent": 5.9},
        {"stock_name": "Axis Bank", "weight_percent": 4.7},
        {"stock_name": "Cholamandalam Investment", "weight_percent": 4.2},
        {"stock_name": "Persistent Systems", "weight_percent": 3.8},
        {"stock_name": "Max Healthcare Institute", "weight_percent": 3.5},
        {"stock_name": "Reliance Industries", "weight_percent": 3.2},
        {"stock_name": "Coforge", "weight_percent": 2.9},
        {"stock_name": "Infosys", "weight_percent": 2.7},
        {"stock_name": "KPIT Technologies", "weight_percent": 2.5},
        {"stock_name": "Indian Hotels", "weight_percent": 2.3},
        {"stock_name": "Bharat Electronics", "weight_percent": 2.1},
        {"stock_name": "Tata Motors", "weight_percent": 1.9},
        {"stock_name": "Bajaj Finance", "weight_percent": 1.7},
        {"stock_name": "Cummins India", "weight_percent": 1.6},
    ],
    "nippon india growth fund": [
        {"stock_name": "BSE Ltd", "weight_percent": 3.32},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 2.68},
        {"stock_name": "Federal Bank Ltd", "weight_percent": 2.5},
        {"stock_name": "AU Small Finance Bank Ltd", "weight_percent": 2.28},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 2.25},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.17},
        {"stock_name": "Info Edge (India) Ltd", "weight_percent": 2.1},
        {"stock_name": "Power Finance Corp Ltd", "weight_percent": 2.01},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 1.95},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 1.85},
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.85},
        {"stock_name": "Voltas Ltd", "weight_percent": 1.82},
        {"stock_name": "Varun Beverages Ltd", "weight_percent": 1.82},
        {"stock_name": "Persistent Systems Ltd", "weight_percent": 1.8},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.8},
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 1.73},
        {"stock_name": "Mankind Pharma Ltd", "weight_percent": 1.7},
        {"stock_name": "NTPC Green Energy Ltd", "weight_percent": 1.69},
        {"stock_name": "Indus Towers Ltd", "weight_percent": 1.68},
        {"stock_name": "Cummins India Ltd", "weight_percent": 1.61},
    ],
    "motilal oswal midcap fund": [
        {"stock_name": "One97 Communications Ltd", "weight_percent": 7.29},
        {"stock_name": "Coforge Ltd", "weight_percent": 6.12},
        {"stock_name": "Kalyan Jewellers India Ltd", "weight_percent": 5.98},
        {"stock_name": "KEI Industries Ltd", "weight_percent": 5.82},
        {"stock_name": "Eternal Ltd", "weight_percent": 5.80},
        {"stock_name": "Persistent Systems Ltd", "weight_percent": 5.74},
        {"stock_name": "Aditya Birla Capital Ltd", "weight_percent": 5.23},
        {"stock_name": "Billionbrains Garage Ventures Ltd", "weight_percent": 4.29},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 4.22},
        {"stock_name": "BSE Ltd", "weight_percent": 3.98},
        {"stock_name": "Tube Investments of India Ltd", "weight_percent": 3.66},
        {"stock_name": "Dixon Technologies (India) Ltd", "weight_percent": 3.58},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 3.24},
        {"stock_name": "Bharti Hexacom Ltd", "weight_percent": 3.08},
        {"stock_name": "Prestige Estates Projects Ltd", "weight_percent": 2.81},
        {"stock_name": "L&T Finance Ltd", "weight_percent": 2.63},
        {"stock_name": "PB Fintech Ltd", "weight_percent": 2.52},
        {"stock_name": "ICICI Prudential Asset Management Co Ltd", "weight_percent": 2.48},
        {"stock_name": "Max Healthcare Institute Ltd", "weight_percent": 2.46},
        {"stock_name": "Bharat Electronics Ltd", "weight_percent": 2.26},
    ],
    "dsp flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.20},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.58},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 5.11},
        {"stock_name": "State Bank of India", "weight_percent": 3.43},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.23},
        {"stock_name": "Cholamandalam Investment and Finance Co Ltd", "weight_percent": 3.07},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.94},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 2.61},
        {"stock_name": "Coforge Ltd", "weight_percent": 2.55},
        {"stock_name": "Cipla Ltd", "weight_percent": 2.24},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 2.23},
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 2.09},
        {"stock_name": "Bharat Petroleum Corp Ltd", "weight_percent": 2.04},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 1.98},
        {"stock_name": "CG Power & Industrial Solutions Ltd", "weight_percent": 1.90},
        {"stock_name": "Radico Khaitan Ltd", "weight_percent": 1.87},
        {"stock_name": "Infosys Ltd", "weight_percent": 1.73},
        {"stock_name": "Polycab India Ltd", "weight_percent": 1.67},
        {"stock_name": "Alkem Laboratories Ltd", "weight_percent": 1.67},
        {"stock_name": "UNO Minda Ltd", "weight_percent": 1.65},
    ],
    "franklin india flexi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.40},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.94},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 5.45},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 4.01},
        {"stock_name": "State Bank of India", "weight_percent": 3.34},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.29},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 3.16},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.04},
        {"stock_name": "Infosys Ltd", "weight_percent": 2.87},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.77},
        {"stock_name": "HCL Technologies Ltd", "weight_percent": 2.56},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.50},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 2.45},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 2.35},
        {"stock_name": "Tata Steel Ltd", "weight_percent": 2.18},
        {"stock_name": "Tata Power Co Ltd", "weight_percent": 2.16},
        {"stock_name": "Marico Ltd", "weight_percent": 2.10},
        {"stock_name": "Grasim Industries Ltd", "weight_percent": 2.02},
        {"stock_name": "NTPC Ltd", "weight_percent": 2.00},
        {"stock_name": "Bharat Electronics Ltd", "weight_percent": 2.00},
    ],
    "jioblackrock flexi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.23},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.59},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.22},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 3.15},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.12},
        {"stock_name": "State Bank of India", "weight_percent": 3.09},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.01},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.84},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 2.20},
        {"stock_name": "NTPC Ltd", "weight_percent": 1.81},
        {"stock_name": "Tata Steel Ltd", "weight_percent": 1.81},
        {"stock_name": "Nestle India Ltd", "weight_percent": 1.80},
        {"stock_name": "Titan Co Ltd", "weight_percent": 1.79},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.69},
        {"stock_name": "Indian Oil Corp Ltd", "weight_percent": 1.66},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 1.60},
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 1.51},
        {"stock_name": "Dr. Lal PathLabs Ltd", "weight_percent": 1.49},
        {"stock_name": "Apollo Tyres Ltd", "weight_percent": 1.44},
        {"stock_name": "ITC Ltd", "weight_percent": 1.42},
    ],
    "axis large cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 9.06},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.22},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 5.04},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 4.78},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.74},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.77},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.53},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.41},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.12},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.06},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.98},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 2.84},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 2.79},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.77},
        {"stock_name": "Titan Co Ltd", "weight_percent": 2.43},
        {"stock_name": "State Bank of India", "weight_percent": 2.31},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.8},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 1.76},
        {"stock_name": "Pidilite Industries Ltd", "weight_percent": 1.62},
        {"stock_name": "NTPC Ltd", "weight_percent": 1.54},
    ],
    "quant flexi cap fund": [
        {"stock_name": "Adani Power Ltd", "weight_percent": 9.99},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 8.56},
        {"stock_name": "Adani Enterprises Ltd", "weight_percent": 8.51},
        {"stock_name": "ICICI Prudential Asset Management Co Ltd", "weight_percent": 6.82},
        {"stock_name": "Aurobindo Pharma Ltd", "weight_percent": 6.13},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.79},
        {"stock_name": "Adani Green Energy Ltd", "weight_percent": 4.43},
        {"stock_name": "Adani Energy Solutions Ltd", "weight_percent": 3.82},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.62},
        {"stock_name": "Tata Power Co Ltd", "weight_percent": 3.53},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.01},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 2.83},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 2.09},
        {"stock_name": "Swan Corp Ltd", "weight_percent": 1.99},
        {"stock_name": "K.P.R. Mill Ltd", "weight_percent": 1.83},
        {"stock_name": "Alivus Life Sciences Ltd", "weight_percent": 1.64},
        {"stock_name": "JSW Infrastructure Ltd", "weight_percent": 1.57},
        {"stock_name": "Indus Infra Trust Unit", "weight_percent": 1.56},
        {"stock_name": "AU Small Finance Bank Ltd", "weight_percent": 1.28},
        {"stock_name": "Piramal Finance Ltd", "weight_percent": 1.02},
    ],
    "hdfc large cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 9.18},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 7.63},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 5.77},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 5.52},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.22},
        {"stock_name": "Titan Co Ltd", "weight_percent": 4.44},
        {"stock_name": "Torrent Pharmaceuticals Ltd", "weight_percent": 3.71},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.65},
        {"stock_name": "Bajaj Auto Ltd", "weight_percent": 3.12},
        {"stock_name": "Bajaj Finserv Ltd", "weight_percent": 3.1},
        {"stock_name": "Infosys Ltd", "weight_percent": 2.98},
        {"stock_name": "Lupin Ltd", "weight_percent": 2.77},
        {"stock_name": "Ambuja Cements Ltd", "weight_percent": 2.64},
        {"stock_name": "NTPC Ltd", "weight_percent": 2.28},
        {"stock_name": "State Bank of India", "weight_percent": 2.22},
        {"stock_name": "Cholamandalam Investment and Finance Co Ltd", "weight_percent": 2.13},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 2.12},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.01},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 1.75},
        {"stock_name": "Tata Motors Ltd", "weight_percent": 1.72},
    ],
    "uti large cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 9.15},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.22},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.35},
        {"stock_name": "Infosys Ltd", "weight_percent": 4.9},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 4.55},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 4.15},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 4.11},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.91},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.8},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 2.59},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.05},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 1.74},
        {"stock_name": "Hindustan Aeronautics Ltd", "weight_percent": 1.68},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 1.63},
        {"stock_name": "Asian Paints Ltd", "weight_percent": 1.44},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 1.43},
        {"stock_name": "Tata Consumer Products Ltd", "weight_percent": 1.42},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 1.42},
        {"stock_name": "State Bank of India", "weight_percent": 1.41},
        {"stock_name": "Avenue Supermarts Ltd", "weight_percent": 1.39},
    ],
    "kotak large cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 6.98},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 6.4},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 6.25},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 4.27},
        {"stock_name": "State Bank of India", "weight_percent": 4.2},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.97},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.25},
        {"stock_name": "NTPC Ltd", "weight_percent": 3.18},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.13},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 2.98},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.45},
        {"stock_name": "Tata Steel Ltd", "weight_percent": 2.26},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.15},
        {"stock_name": "Solar Industries India Ltd", "weight_percent": 2.13},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.09},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.81},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 1.79},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.75},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 1.63},
        {"stock_name": "Torrent Pharmaceuticals Ltd", "weight_percent": 1.58},
    ],
    "aditya birla sun life large cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 7.17},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 6.63},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 5.26},
        {"stock_name": "Infosys Ltd", "weight_percent": 4.21},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.93},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.6},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.49},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.42},
        {"stock_name": "State Bank of India", "weight_percent": 3.34},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 3.22},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.14},
        {"stock_name": "Hindalco Industries Ltd", "weight_percent": 1.97},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.96},
        {"stock_name": "NTPC Ltd", "weight_percent": 1.82},
        {"stock_name": "SBI Life Insurance Co Ltd", "weight_percent": 1.77},
        {"stock_name": "Adani Energy Solutions Ltd", "weight_percent": 1.73},
        {"stock_name": "United Spirits Ltd", "weight_percent": 1.64},
        {"stock_name": "Bajaj Auto Ltd", "weight_percent": 1.5},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.4},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 1.38},
    ],
    "hdfc large and mid cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 3.83},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 3.48},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.92},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 1.86},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 1.59},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 1.54},
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 1.53},
        {"stock_name": "State Bank of India", "weight_percent": 1.42},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 1.35},
        {"stock_name": "Infosys Ltd", "weight_percent": 1.32},
        {"stock_name": "Prestige Estates Projects Ltd", "weight_percent": 1.25},
        {"stock_name": "Mphasis Ltd", "weight_percent": 1.23},
        {"stock_name": "IndusInd Bank Ltd", "weight_percent": 1.21},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.13},
        {"stock_name": "Lupin Ltd", "weight_percent": 1.11},
        {"stock_name": "Gland Pharma Ltd", "weight_percent": 1.1},
        {"stock_name": "Aurobindo Pharma Ltd", "weight_percent": 1.08},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.07},
        {"stock_name": "Mahindra & Mahindra Financial Services Ltd", "weight_percent": 1.05},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 1.04},
    ],
    "quant large cap fund": [
        {"stock_name": "Adani Green Energy Ltd", "weight_percent": 9.82},
        {"stock_name": "Adani Enterprises Ltd", "weight_percent": 9.24},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 8.73},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 8.53},
        {"stock_name": "ICICI Prudential Asset Management Co Ltd", "weight_percent": 7.35},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 6.67},
        {"stock_name": "Capri Global Capital Ltd", "weight_percent": 6.27},
        {"stock_name": "LG Electronics India Ltd", "weight_percent": 5.77},
        {"stock_name": "Adani Energy Solutions Ltd", "weight_percent": 4.68},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.75},
        {"stock_name": "Tech Mahindra Ltd", "weight_percent": 1.96},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 1.14},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.02},
    ],
    "groww small cap fund": [
        {"stock_name": "TD Power Systems Ltd", "weight_percent": 4.39},
        {"stock_name": "Tamilnad Mercantile Bank Ltd", "weight_percent": 3.68},
        {"stock_name": "Home First Finance Co India Ltd", "weight_percent": 3.63},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 3.44},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 3.38},
        {"stock_name": "Ujjivan Small Finance Bank Ltd", "weight_percent": 3.33},
        {"stock_name": "Azad Engineering Ltd", "weight_percent": 2.92},
        {"stock_name": "Prudent Corporate Advisory Services Ltd", "weight_percent": 2.82},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 2.73},
        {"stock_name": "Craftsman Automation Ltd", "weight_percent": 2.73},
        {"stock_name": "SBFC Finance Ltd", "weight_percent": 2.63},
        {"stock_name": "CreditAccess Grameen Ltd", "weight_percent": 2.58},
        {"stock_name": "RBL Bank Ltd", "weight_percent": 2.35},
        {"stock_name": "Galaxy Surfactants Ltd", "weight_percent": 2.29},
        {"stock_name": "L G Balakrishnan & Bros Ltd", "weight_percent": 2.28},
        {"stock_name": "Yatharth Hospital & Trauma Care Services Ltd", "weight_percent": 2.27},
        {"stock_name": "Tenneco Clean Air India Ltd", "weight_percent": 2.16},
        {"stock_name": "Sharda Motor Industries Ltd", "weight_percent": 2.11},
        {"stock_name": "OnEMI Technology Solutions Ltd", "weight_percent": 2.08},
        {"stock_name": "Fine Organic Industries Ltd", "weight_percent": 2.07},
    ],
    "mirae asset small cap fund": [
        {"stock_name": "Welspun Corp Ltd", "weight_percent": 3.02},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 2.93},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 2.57},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 2.53},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.24},
        {"stock_name": "Voltamp Transformers Ltd", "weight_percent": 2.22},
        {"stock_name": "Dr Lal PathLabs Ltd", "weight_percent": 2.19},
        {"stock_name": "Anthem Biosciences Ltd", "weight_percent": 2.14},
        {"stock_name": "Timken India Ltd", "weight_percent": 2.11},
        {"stock_name": "Neuland Laboratories Ltd", "weight_percent": 2.09},
        {"stock_name": "Godawari Power & Ispat Ltd", "weight_percent": 2.04},
        {"stock_name": "Triveni Turbine Ltd", "weight_percent": 2.03},
        {"stock_name": "Atul Ltd", "weight_percent": 1.99},
        {"stock_name": "J B Chemicals & Pharmaceuticals Ltd", "weight_percent": 1.98},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.82},
        {"stock_name": "Tenneco Clean Air India Ltd", "weight_percent": 1.8},
        {"stock_name": "CRISIL Ltd", "weight_percent": 1.77},
        {"stock_name": "Computer Age Management Services Ltd", "weight_percent": 1.77},
        {"stock_name": "Central Depository Services (India) Ltd", "weight_percent": 1.74},
        {"stock_name": "JK Cement Ltd", "weight_percent": 1.74},
    ],
    "uti small cap fund": [
        {"stock_name": "TD Power Systems Ltd", "weight_percent": 2.92},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 2.55},
        {"stock_name": "Acutaas Chemicals Ltd", "weight_percent": 2.45},
        {"stock_name": "Navin Fluorine International Ltd", "weight_percent": 2.1},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 2.02},
        {"stock_name": "INOX India Ltd", "weight_percent": 1.89},
        {"stock_name": "MTAR Technologies Ltd", "weight_percent": 1.86},
        {"stock_name": "Ujjivan Small Finance Bank Ltd", "weight_percent": 1.84},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 1.74},
        {"stock_name": "Affle (India) Ltd", "weight_percent": 1.74},
        {"stock_name": "Jubilant Ingrevia Ltd", "weight_percent": 1.65},
        {"stock_name": "Marksans Pharma Ltd", "weight_percent": 1.59},
        {"stock_name": "Eris Lifesciences Ltd", "weight_percent": 1.54},
        {"stock_name": "Delhivery Ltd", "weight_percent": 1.54},
        {"stock_name": "Caplin Point Laboratories Ltd", "weight_percent": 1.53},
        {"stock_name": "KFin Technologies Ltd", "weight_percent": 1.42},
        {"stock_name": "Tips Music Ltd", "weight_percent": 1.41},
        {"stock_name": "Aditya Birla Capital Ltd", "weight_percent": 1.41},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.39},
        {"stock_name": "India Shelter Finance Corp Ltd", "weight_percent": 1.34},
    ],
    "edelweiss small cap fund": [
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 3.37},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 3.12},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 2.58},
        {"stock_name": "Avalon Technologies Ltd", "weight_percent": 2.44},
        {"stock_name": "KEI Industries Ltd", "weight_percent": 2.38},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 2.27},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.16},
        {"stock_name": "Ajanta Pharma Ltd", "weight_percent": 2.14},
        {"stock_name": "Radico Khaitan Ltd", "weight_percent": 2.11},
        {"stock_name": "Gabriel India Ltd", "weight_percent": 1.96},
        {"stock_name": "PNB Housing Finance Ltd", "weight_percent": 1.95},
        {"stock_name": "Indian Bank", "weight_percent": 1.89},
        {"stock_name": "UNO Minda Ltd", "weight_percent": 1.86},
        {"stock_name": "Bikaji Foods International Ltd", "weight_percent": 1.77},
        {"stock_name": "Inventurus Knowledge Solutions Ltd", "weight_percent": 1.77},
        {"stock_name": "Century Plyboards (India) Ltd", "weight_percent": 1.74},
        {"stock_name": "Equitas Small Finance Bank Ltd", "weight_percent": 1.74},
        {"stock_name": "J B Chemicals & Pharmaceuticals Ltd", "weight_percent": 1.66},
        {"stock_name": "APL Apollo Tubes Ltd", "weight_percent": 1.65},
        {"stock_name": "Kirloskar Pneumatic Co Ltd", "weight_percent": 1.62},
    ],
    "motilal oswal small cap fund": [
        {"stock_name": "VA Tech Wabag Ltd", "weight_percent": 3.89},
        {"stock_name": "Aditya Infotech Ltd", "weight_percent": 3.84},
        {"stock_name": "Rubicon Research Ltd", "weight_percent": 3.8},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 3.66},
        {"stock_name": "CCL Products (India) Ltd", "weight_percent": 3.58},
        {"stock_name": "Vijaya Diagnostic Centre Ltd", "weight_percent": 3.33},
        {"stock_name": "Dr Agarwals Health Care Ltd", "weight_percent": 3.17},
        {"stock_name": "Shaily Engineering Plastics Ltd", "weight_percent": 2.98},
        {"stock_name": "Campus Activewear Ltd", "weight_percent": 2.7},
        {"stock_name": "Rainbow Childrens Medicare Ltd", "weight_percent": 2.43},
        {"stock_name": "Pricol Ltd", "weight_percent": 2.35},
        {"stock_name": "Sky Gold Ltd", "weight_percent": 2.33},
        {"stock_name": "Asahi India Glass Ltd", "weight_percent": 2.31},
        {"stock_name": "V2 Retail Ltd", "weight_percent": 2.21},
        {"stock_name": "Syrma SGS Technology Ltd", "weight_percent": 2.18},
        {"stock_name": "Gabriel India Ltd", "weight_percent": 2.13},
        {"stock_name": "V-Mart Retail Ltd", "weight_percent": 2.12},
        {"stock_name": "Aditya Vision Ltd", "weight_percent": 2.0},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 1.95},
        {"stock_name": "Five-Star Business Finance Ltd", "weight_percent": 1.85},
    ],
    "icici prudential small cap fund": [
        {"stock_name": "Atul Ltd", "weight_percent": 2.68},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 2.5},
        {"stock_name": "Timken India Ltd", "weight_percent": 2.25},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.13},
        {"stock_name": "Shadowfax Technologies Ltd", "weight_percent": 2.08},
        {"stock_name": "Minda Corp Ltd", "weight_percent": 2.07},
        {"stock_name": "Gujarat Pipavav Port Ltd", "weight_percent": 1.89},
        {"stock_name": "Pfizer Ltd", "weight_percent": 1.88},
        {"stock_name": "TVS Holdings Ltd", "weight_percent": 1.87},
        {"stock_name": "Tata Chemicals Ltd", "weight_percent": 1.7},
        {"stock_name": "Carborundum Universal Ltd", "weight_percent": 1.67},
        {"stock_name": "Triveni Turbine Ltd", "weight_percent": 1.66},
        {"stock_name": "EIH Ltd", "weight_percent": 1.65},
        {"stock_name": "Gujarat Gas Ltd", "weight_percent": 1.62},
        {"stock_name": "Grindwell Norton Ltd", "weight_percent": 1.49},
        {"stock_name": "Sedemac Mechatronics Pvt Ltd", "weight_percent": 1.45},
        {"stock_name": "LIC Housing Finance Ltd", "weight_percent": 1.44},
        {"stock_name": "GNFC Ltd", "weight_percent": 1.41},
        {"stock_name": "Netweb Technologies India Ltd", "weight_percent": 1.37},
        {"stock_name": "Page Industries Ltd", "weight_percent": 1.21},
    ],
    "tata small cap fund": [
        {"stock_name": "Kirloskar Pneumatic Co Ltd", "weight_percent": 5.68},
        {"stock_name": "Usha Martin Ltd", "weight_percent": 5.05},
        {"stock_name": "Sudarshan Chemical Industries Ltd", "weight_percent": 4.02},
        {"stock_name": "Tega Industries Ltd", "weight_percent": 3.87},
        {"stock_name": "Godrej Industries Ltd", "weight_percent": 3.76},
        {"stock_name": "Wockhardt Ltd", "weight_percent": 3.66},
        {"stock_name": "IDFC First Bank Ltd", "weight_percent": 3.66},
        {"stock_name": "Cello World Ltd", "weight_percent": 2.4},
        {"stock_name": "Graphite India Ltd", "weight_percent": 2.35},
        {"stock_name": "BASF India Ltd", "weight_percent": 2.23},
        {"stock_name": "Time Technoplast Ltd", "weight_percent": 2.13},
        {"stock_name": "Carborundum Universal Ltd", "weight_percent": 2.11},
        {"stock_name": "CE Info Systems Ltd", "weight_percent": 1.97},
        {"stock_name": "Anant Raj Ltd", "weight_percent": 1.81},
        {"stock_name": "Wonderla Holidays Ltd", "weight_percent": 1.75},
        {"stock_name": "Sundaram Clayton Ltd", "weight_percent": 1.74},
        {"stock_name": "DCB Bank Ltd", "weight_percent": 1.71},
        {"stock_name": "SAMHI Hotels Ltd", "weight_percent": 1.69},
        {"stock_name": "ELANTAS Beck India Ltd", "weight_percent": 1.66},
        {"stock_name": "Quess Corp Ltd", "weight_percent": 1.65},
    ],
    "franklin india small cap fund": [
        {"stock_name": "Equitas Small Finance Bank Ltd", "weight_percent": 2.44},
        {"stock_name": "Syrma SGS Technology Ltd", "weight_percent": 2.38},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 2.28},
        {"stock_name": "Eris Lifesciences Ltd", "weight_percent": 2.26},
        {"stock_name": "MTAR Technologies Ltd", "weight_percent": 2.23},
        {"stock_name": "Kajaria Ceramics Ltd", "weight_percent": 2.22},
        {"stock_name": "PNB Housing Finance Ltd", "weight_percent": 2.03},
        {"stock_name": "Angel One Ltd", "weight_percent": 1.98},
        {"stock_name": "Brigade Enterprises Ltd", "weight_percent": 1.82},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 1.8},
        {"stock_name": "CESC Ltd", "weight_percent": 1.76},
        {"stock_name": "Metropolis Healthcare Ltd", "weight_percent": 1.75},
        {"stock_name": "Deepak Nitrite Ltd", "weight_percent": 1.69},
        {"stock_name": "Hindustan Aeronautics Ltd", "weight_percent": 1.66},
        {"stock_name": "Crompton Greaves Consumer Electricals Ltd", "weight_percent": 1.63},
        {"stock_name": "Sobha Ltd", "weight_percent": 1.55},
        {"stock_name": "DCB Bank Ltd", "weight_percent": 1.54},
        {"stock_name": "Medplus Health Services Ltd", "weight_percent": 1.53},
        {"stock_name": "Data Patterns (India) Ltd", "weight_percent": 1.53},
        {"stock_name": "Zensar Technologies Ltd", "weight_percent": 1.49},
    ],
    "kotak small cap fund": [
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 4.63},
        {"stock_name": "Vijaya Diagnostic Centre Ltd", "weight_percent": 4.04},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 3.6},
        {"stock_name": "Sansera Engineering Ltd", "weight_percent": 3.34},
        {"stock_name": "Kalpataru Projects International Ltd", "weight_percent": 2.62},
        {"stock_name": "Century Plyboards (India) Ltd", "weight_percent": 2.53},
        {"stock_name": "Minda Corp Ltd", "weight_percent": 2.32},
        {"stock_name": "Techno Electric & Engineering Co Ltd", "weight_percent": 2.21},
        {"stock_name": "Metropolis Healthcare Ltd", "weight_percent": 1.99},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.92},
        {"stock_name": "Ajanta Pharma Ltd", "weight_percent": 1.88},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 1.86},
        {"stock_name": "Medplus Health Services Ltd", "weight_percent": 1.8},
        {"stock_name": "Five-Star Business Finance Ltd", "weight_percent": 1.74},
        {"stock_name": "Garware Technical Fibres Ltd", "weight_percent": 1.72},
        {"stock_name": "Cyient Ltd", "weight_percent": 1.69},
        {"stock_name": "Aptus Value Housing Finance India Ltd", "weight_percent": 1.66},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.58},
        {"stock_name": "Brigade Enterprises Ltd", "weight_percent": 1.51},
        {"stock_name": "Vishal Mega Mart Ltd", "weight_percent": 1.43},
    ],
    "dsp small cap fund": [
        {"stock_name": "Lumax Auto Technologies Ltd", "weight_percent": 5.01},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 3.95},
        {"stock_name": "Thangamayil Jewellery Ltd", "weight_percent": 3.42},
        {"stock_name": "Sansera Engineering Ltd", "weight_percent": 2.76},
        {"stock_name": "Welspun Corp Ltd", "weight_percent": 2.56},
        {"stock_name": "Jubilant Ingrevia Ltd", "weight_percent": 2.45},
        {"stock_name": "Dodla Dairy Ltd", "weight_percent": 2.21},
        {"stock_name": "LT Foods Ltd", "weight_percent": 2.14},
        {"stock_name": "SPR Auto Technologies Ltd", "weight_percent": 2.0},
        {"stock_name": "eClerx Services Ltd", "weight_percent": 1.82},
        {"stock_name": "Triveni Engineering & Industries Ltd", "weight_percent": 1.81},
        {"stock_name": "Ipca Laboratories Ltd", "weight_percent": 1.74},
        {"stock_name": "Gland Pharma Ltd", "weight_percent": 1.61},
        {"stock_name": "Dhanuka Agritech Ltd", "weight_percent": 1.53},
        {"stock_name": "Swaraj Engines Ltd", "weight_percent": 1.53},
        {"stock_name": "Harsha Engineers International Ltd", "weight_percent": 1.51},
        {"stock_name": "Atul Ltd", "weight_percent": 1.51},
        {"stock_name": "Prudent Corporate Advisory Services Ltd", "weight_percent": 1.49},
        {"stock_name": "Suprajit Engineering Ltd", "weight_percent": 1.49},
        {"stock_name": "Cyient Ltd", "weight_percent": 1.48},
    ],
    "hdfc small cap fund": [
        {"stock_name": "Firstsource Solutions Ltd", "weight_percent": 3.92},
        {"stock_name": "Aster DM Healthcare Ltd", "weight_percent": 3.8},
        {"stock_name": "Bank of Baroda", "weight_percent": 3.24},
        {"stock_name": "Gabriel India Ltd", "weight_percent": 2.77},
        {"stock_name": "eClerx Services Ltd", "weight_percent": 2.45},
        {"stock_name": "Eris Lifesciences Ltd", "weight_percent": 2.37},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 2.26},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 2.18},
        {"stock_name": "Indian Bank", "weight_percent": 2.08},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 1.71},
        {"stock_name": "Great Eastern Shipping Co Ltd", "weight_percent": 1.66},
        {"stock_name": "Timken India Ltd", "weight_percent": 1.63},
        {"stock_name": "Kalpataru Projects International Ltd", "weight_percent": 1.56},
        {"stock_name": "Federal Bank Ltd", "weight_percent": 1.55},
        {"stock_name": "Home First Finance Co India Ltd", "weight_percent": 1.47},
        {"stock_name": "PVR INOX Ltd", "weight_percent": 1.42},
        {"stock_name": "Power Mech Projects Ltd", "weight_percent": 1.42},
        {"stock_name": "Sudarshan Chemical Industries Ltd", "weight_percent": 1.4},
        {"stock_name": "Vardhman Textiles Ltd", "weight_percent": 1.4},
        {"stock_name": "Suprajit Engineering Ltd", "weight_percent": 1.39},
    ],
    "aditya birla sun life flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.72},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 3.43},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.41},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 2.90},
        {"stock_name": "Infosys Ltd", "weight_percent": 2.75},
        {"stock_name": "Hindalco Industries Ltd", "weight_percent": 2.38},
        {"stock_name": "State Bank of India", "weight_percent": 2.26},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.18},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 2.17},
        {"stock_name": "HCL Technologies Ltd", "weight_percent": 1.87},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.73},
        {"stock_name": "Godrej Consumer Products Ltd", "weight_percent": 1.73},
        {"stock_name": "SBI Life Insurance Co Ltd", "weight_percent": 1.69},
        {"stock_name": "Ather Energy Ltd", "weight_percent": 1.67},
        {"stock_name": "Jindal Steel Ltd", "weight_percent": 1.66},
        {"stock_name": "Sona BLW Precision Forgings Ltd", "weight_percent": 1.63},
        {"stock_name": "United Spirits Ltd", "weight_percent": 1.61},
        {"stock_name": "Tech Mahindra Ltd", "weight_percent": 1.61},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 1.59},
        {"stock_name": "Lenskart Solutions Ltd", "weight_percent": 1.58},
    ],
    "axis flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 7.49},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 3.94},
        {"stock_name": "Bharat Electronics Ltd", "weight_percent": 3.84},
        {"stock_name": "Eternal Ltd", "weight_percent": 3.71},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.38},
        {"stock_name": "Krishna Institute of Medical Sciences Ltd", "weight_percent": 3.27},
        {"stock_name": "State Bank of India", "weight_percent": 3.21},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 3.12},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 2.90},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.62},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 2.46},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.34},
        {"stock_name": "CG Power & Industrial Solutions Ltd", "weight_percent": 2.23},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 2.21},
        {"stock_name": "PB Fintech Ltd", "weight_percent": 2.13},
        {"stock_name": "Cholamandalam Investment and Finance Co Ltd", "weight_percent": 1.97},
        {"stock_name": "InterGlobe Aviation Ltd", "weight_percent": 1.94},
        {"stock_name": "Mankind Pharma Ltd", "weight_percent": 1.93},
        {"stock_name": "Sansera Engineering Ltd", "weight_percent": 1.80},
        {"stock_name": "TVS Motor Co Ltd", "weight_percent": 1.73},
    ],
    "axis multicap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 3.51},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 3.47},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 2.47},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 2.00},
        {"stock_name": "Sona BLW Precision Forgings Ltd", "weight_percent": 1.98},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 1.84},
        {"stock_name": "Minda Corp Ltd", "weight_percent": 1.80},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 1.75},
        {"stock_name": "Apar Industries Ltd", "weight_percent": 1.74},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 1.74},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 1.74},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 1.61},
        {"stock_name": "Craftsman Automation Ltd", "weight_percent": 1.59},
        {"stock_name": "RBL Bank Ltd", "weight_percent": 1.56},
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.56},
        {"stock_name": "Sansera Engineering Ltd", "weight_percent": 1.55},
        {"stock_name": "Welspun Corp Ltd", "weight_percent": 1.52},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 1.48},
        {"stock_name": "State Bank of India", "weight_percent": 1.46},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.44},
    ],
    "bandhan flexi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 8.11},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 7.32},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 4.37},
        {"stock_name": "Infosys Ltd", "weight_percent": 3.68},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 3.63},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.55},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.53},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 3.11},
        {"stock_name": "ITC Ltd", "weight_percent": 2.87},
        {"stock_name": "Bajaj Finserv Ltd", "weight_percent": 2.70},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 2.62},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 2.19},
        {"stock_name": "Sterlite Technologies Ltd", "weight_percent": 1.97},
        {"stock_name": "Eternal Ltd", "weight_percent": 1.93},
        {"stock_name": "HDFC Life Insurance Co Ltd", "weight_percent": 1.93},
        {"stock_name": "Titan Co Ltd", "weight_percent": 1.74},
        {"stock_name": "Apollo Hospitals Enterprise Ltd", "weight_percent": 1.63},
        {"stock_name": "Cholamandalam Financial Holdings Ltd", "weight_percent": 1.57},
        {"stock_name": "Oil & Natural Gas Corp Ltd", "weight_percent": 1.55},
        {"stock_name": "Cipla Ltd", "weight_percent": 1.35},
    ],
    "bandhan multi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 4.97},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 3.60},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 3.55},
        {"stock_name": "Sterlite Technologies Ltd", "weight_percent": 2.94},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 2.58},
        {"stock_name": "Infosys Ltd", "weight_percent": 1.99},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 1.98},
        {"stock_name": "Tata Consultancy Services Ltd", "weight_percent": 1.93},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 1.82},
        {"stock_name": "Maruti Suzuki India Ltd", "weight_percent": 1.80},
        {"stock_name": "Mahindra & Mahindra Financial Services Ltd", "weight_percent": 1.61},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 1.57},
        {"stock_name": "ICICI Lombard General Insurance Co Ltd", "weight_percent": 1.53},
        {"stock_name": "Poonawalla Fincorp Ltd", "weight_percent": 1.41},
        {"stock_name": "IDFC First Bank Ltd", "weight_percent": 1.39},
        {"stock_name": "Dr Reddy's Laboratories Ltd", "weight_percent": 1.34},
        {"stock_name": "RBL Bank Ltd", "weight_percent": 1.30},
        {"stock_name": "Titan Co Ltd", "weight_percent": 1.26},
        {"stock_name": "V-Mart Retail Ltd", "weight_percent": 1.26},
        {"stock_name": "Nestle India Ltd", "weight_percent": 1.22},
    ],
    "canara robeco flexi cap fund": [
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 6.69},
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 6.18},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 3.76},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 3.71},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 3.32},
        {"stock_name": "State Bank of India", "weight_percent": 3.16},
        {"stock_name": "Infosys Ltd", "weight_percent": 2.99},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 2.59},
        {"stock_name": "Axis Bank Ltd", "weight_percent": 2.53},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 2.41},
        {"stock_name": "Eternal Ltd", "weight_percent": 2.29},
        {"stock_name": "Varun Beverages Ltd", "weight_percent": 1.74},
        {"stock_name": "TVS Motor Co Ltd", "weight_percent": 1.71},
        {"stock_name": "Sun Pharmaceuticals Industries Ltd", "weight_percent": 1.70},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.59},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 1.45},
        {"stock_name": "KEI Industries Ltd", "weight_percent": 1.43},
        {"stock_name": "Tech Mahindra Ltd", "weight_percent": 1.42},
        {"stock_name": "UNO Minda Ltd", "weight_percent": 1.39},
        {"stock_name": "Tata Consumer Products Ltd", "weight_percent": 1.37},
    ],
    "dsp midcap fund": [
        {"stock_name": "Coforge Ltd", "weight_percent": 3.93},
        {"stock_name": "Cholamandalam Investment and Finance Co Ltd", "weight_percent": 2.72},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 2.70},
        {"stock_name": "Nippon Life India Asset Management Ltd", "weight_percent": 2.54},
        {"stock_name": "Max Financial Services Ltd", "weight_percent": 2.51},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 2.40},
        {"stock_name": "Phoenix Mills Ltd", "weight_percent": 2.37},
        {"stock_name": "Ipca Laboratories Ltd", "weight_percent": 2.32},
        {"stock_name": "The Federal Bank Ltd", "weight_percent": 2.30},
        {"stock_name": "Voltas Ltd", "weight_percent": 2.30},
        {"stock_name": "Jindal Steel Ltd", "weight_percent": 2.28},
        {"stock_name": "Coromandel International Ltd", "weight_percent": 2.27},
        {"stock_name": "KEI Industries Ltd", "weight_percent": 2.23},
        {"stock_name": "Schaeffler India Ltd", "weight_percent": 2.20},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 2.20},
        {"stock_name": "AU Small Finance Bank Ltd", "weight_percent": 2.15},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 2.09},
        {"stock_name": "Supreme Industries Ltd", "weight_percent": 2.05},
        {"stock_name": "Kirloskar Oil Engines Ltd", "weight_percent": 1.93},
        {"stock_name": "Samvardhana Motherson International Ltd", "weight_percent": 1.90},
    ],
    "edelweiss flexi cap fund": [
        {"stock_name": "ICICI Bank Ltd", "weight_percent": 5.47},
        {"stock_name": "HDFC Bank Ltd", "weight_percent": 5.45},
        {"stock_name": "Larsen & Toubro Ltd", "weight_percent": 4.03},
        {"stock_name": "NTPC Ltd", "weight_percent": 3.36},
        {"stock_name": "Reliance Industries Ltd", "weight_percent": 3.11},
        {"stock_name": "Tata Steel Ltd", "weight_percent": 2.50},
        {"stock_name": "State Bank of India", "weight_percent": 2.44},
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 2.14},
        {"stock_name": "UltraTech Cement Ltd", "weight_percent": 1.87},
        {"stock_name": "Bharti Airtel Ltd", "weight_percent": 1.82},
        {"stock_name": "Bajaj Finance Ltd", "weight_percent": 1.75},
        {"stock_name": "Karur Vysya Bank Ltd", "weight_percent": 1.63},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 1.63},
        {"stock_name": "Titan Co Ltd", "weight_percent": 1.57},
        {"stock_name": "Shriram Finance Ltd", "weight_percent": 1.50},
        {"stock_name": "Divi's Laboratories Ltd", "weight_percent": 1.47},
        {"stock_name": "Kotak Mahindra Bank Ltd", "weight_percent": 1.47},
        {"stock_name": "City Union Bank Ltd", "weight_percent": 1.41},
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 1.37},
        {"stock_name": "Mahindra & Mahindra Ltd", "weight_percent": 1.35},
    ],
    "edelweiss mid cap fund": [
        {"stock_name": "Multi Commodity Exchange of India Ltd", "weight_percent": 3.03},
        {"stock_name": "BSE Ltd", "weight_percent": 2.94},
        {"stock_name": "The Federal Bank Ltd", "weight_percent": 2.90},
        {"stock_name": "Fortis Healthcare Ltd", "weight_percent": 2.23},
        {"stock_name": "Marico Ltd", "weight_percent": 2.22},
        {"stock_name": "Solar Industries India Ltd", "weight_percent": 2.14},
        {"stock_name": "Bharat Heavy Electricals Ltd", "weight_percent": 2.00},
        {"stock_name": "JSW Energy Ltd", "weight_percent": 1.91},
        {"stock_name": "Indian Bank", "weight_percent": 1.65},
        {"stock_name": "Coforge Ltd", "weight_percent": 1.63},
        {"stock_name": "IDFC First Bank Ltd", "weight_percent": 1.63},
        {"stock_name": "Cummins India Ltd", "weight_percent": 1.61},
        {"stock_name": "GE Vernova T&D India Ltd", "weight_percent": 1.57},
        {"stock_name": "NMDC Ltd", "weight_percent": 1.56},
        {"stock_name": "Persistent Systems Ltd", "weight_percent": 1.56},
        {"stock_name": "AU Small Finance Bank Ltd", "weight_percent": 1.55},
        {"stock_name": "Radico Khaitan Ltd", "weight_percent": 1.53},
        {"stock_name": "Bharat Forge Ltd", "weight_percent": 1.53},
        {"stock_name": "Indus Towers Ltd", "weight_percent": 1.53},
        {"stock_name": "L&T Finance Ltd", "weight_percent": 1.51},
    ],
}

# Aliases for common name variations
FUND_ALIASES = {
    "axis bluechip": "axis bluechip fund",
    "mirae asset large cap": "mirae asset large cap fund",
    "mirae large cap": "mirae asset large cap fund",
    "hdfc flexi cap": "hdfc flexi cap fund",
    "hdfc flexicap": "hdfc flexi cap fund",
    "hdfc top 100": "hdfc top 100 fund",
    "sbi bluechip": "sbi bluechip fund",
    "icici pru bluechip": "icici prudential bluechip fund",
    "icici prudential bluechip": "icici prudential bluechip fund",
    "parag parikh flexi cap": "parag parikh flexi cap fund",
    "ppfas flexi cap": "parag parikh flexi cap fund",
    "kotak flexi cap": "kotak flexicap fund",
    "kotak flexicap": "kotak flexicap fund",
    "jioblackrock flexi cap": "jioblackrock flexi cap fund",
    "jio blackrock flexi cap": "jioblackrock flexi cap fund",
    "nippon india growth mid cap": "nippon india growth fund",
    "nippon india mid cap": "nippon india growth fund",
    "nippon large cap": "nippon india large cap fund",
    "canara robeco bluechip": "canara robeco bluechip equity fund",
    "sbi small cap": "sbi small cap fund",
    "nippon small cap": "nippon india small cap fund",
    "axis small cap": "axis small cap fund",
    "bandhan small cap": "bandhan small cap fund",
    "quant small cap": "quant small cap fund",
    "hdfc mid cap": "hdfc mid-cap opportunities fund",
    "hdfc midcap": "hdfc mid-cap opportunities fund",
    "kotak emerging equity": "kotak emerging equity fund",
    "axis midcap": "axis midcap fund",
    "axis mid cap": "axis midcap fund",
    "mirae emerging bluechip": "mirae asset emerging bluechip fund",
    "mirae asset emerging": "mirae asset emerging bluechip fund",
    "motilal midcap": "motilal oswal midcap fund",
    "motilal oswal midcap": "motilal oswal midcap fund",
    "dsp flexi cap": "dsp flexi cap fund",
    "dsp flexicap": "dsp flexi cap fund",
    "franklin flexi cap": "franklin india flexi cap fund",
    "quant flexi cap": "quant flexi cap fund",
    "axis large cap": "axis large cap fund",
    "icici prudential large cap": "icici prudential bluechip fund",
    "icici pru large cap": "icici prudential bluechip fund",
    "hdfc large cap": "hdfc large cap fund",
    "uti large cap": "uti large cap fund",
    "uti nifty 200": "uti large cap fund",
    "kotak large cap": "kotak large cap fund",
    "kotak bluechip": "kotak large cap fund",
    "aditya birla large cap": "aditya birla sun life large cap fund",
    "abl large cap": "aditya birla sun life large cap fund",
    "absl large cap": "aditya birla sun life large cap fund",
    "birla large cap": "aditya birla sun life large cap fund",
    "hdfc large mid cap": "hdfc large and mid cap fund",
    "hdfc large and mid cap": "hdfc large and mid cap fund",
    "quant large cap": "quant large cap fund",
    "sbi large cap": "sbi bluechip fund",
    "groww small cap": "groww small cap fund",
    "mirae asset small cap": "mirae asset small cap fund",
    "mirae small cap": "mirae asset small cap fund",
    "uti small cap": "uti small cap fund",
    "edelweiss small cap": "edelweiss small cap fund",
    "motilal oswal small cap": "motilal oswal small cap fund",
    "motilal small cap": "motilal oswal small cap fund",
    "icici pru small cap": "icici prudential small cap fund",
    "icici prudential smallcap": "icici prudential small cap fund",
    "icici smallcap": "icici prudential small cap fund",
    "tata small cap": "tata small cap fund",
    "franklin india small cap": "franklin india small cap fund",
    "franklin small cap": "franklin india small cap fund",
    "kotak small cap": "kotak small cap fund",
    "dsp small cap": "dsp small cap fund",
    "hdfc small cap": "hdfc small cap fund",
    "aditya birla flexi cap": "aditya birla sun life flexi cap fund",
    "absl flexi cap": "aditya birla sun life flexi cap fund",
    "aditya birla sun life flexi cap": "aditya birla sun life flexi cap fund",
    "birla flexi cap": "aditya birla sun life flexi cap fund",
    "axis flexi cap": "axis flexi cap fund",
    "axis flexicap": "axis flexi cap fund",
    "axis multicap": "axis multicap fund",
    "axis multi cap": "axis multicap fund",
    "bandhan flexi cap": "bandhan flexi cap fund",
    "bandhan flexicap": "bandhan flexi cap fund",
    "bandhan multi cap": "bandhan multi cap fund",
    "bandhan multicap": "bandhan multi cap fund",
    "canara robeco flexi cap": "canara robeco flexi cap fund",
    "canara robeco flexicap": "canara robeco flexi cap fund",
    "dsp midcap": "dsp midcap fund",
    "dsp mid cap": "dsp midcap fund",
    "edelweiss flexi cap": "edelweiss flexi cap fund",
    "edelweiss flexicap": "edelweiss flexi cap fund",
    "edelweiss mid cap": "edelweiss mid cap fund",
    "edelweiss midcap": "edelweiss mid cap fund",
}


def _clean_fund_name(fund_name: str) -> str:
    """Normalize fund name for matching."""
    import re
    name = fund_name.lower().strip()
    # Replace hyphens with spaces
    name = name.replace("-", " ")
    # Remove noise words/suffixes
    noise = [
        "non demat", "demat", "direct plan", "regular plan", "direct",
        "regular", "growth", "idcw", "dividend", "payout", "reinvestment",
        r"\(g\)", r"\(d\)", r"\(idcw\)", r"\(nr\)", r"\(non demat\)",
        r"\(demat\)", "plan", "option",
    ]
    for n in noise:
        name = re.sub(r"\b" + n + r"\b", " ", name)
    # Collapse whitespace
    name = re.sub(r"\s+", " ", name).strip()
    return name


def lookup_fund_holdings(fund_name: str):
    """Look up holdings from static DB using fuzzy matching. Returns (holdings, matched_name) or (None, None)."""
    from difflib import SequenceMatcher

    name = _clean_fund_name(fund_name)

    # Check aliases first (also clean alias keys)
    for alias, canonical in FUND_ALIASES.items():
        if alias in name or name in alias:
            return FUND_HOLDINGS[canonical], canonical

    # Try exact key match
    if name in FUND_HOLDINGS:
        return FUND_HOLDINGS[name], name

    # Fuzzy match against all keys
    best_score = 0.0
    best_key = None
    for key in FUND_HOLDINGS:
        clean_key = _clean_fund_name(key)
        score = SequenceMatcher(None, name, clean_key).ratio()
        if score > best_score:
            best_score = score
            best_key = key

    print(f"  Fund lookup '{name}' -> best='{best_key}' score={best_score:.2f}")
    if best_score >= 0.62:
        return FUND_HOLDINGS[best_key], best_key

    return None, None
