# Stock → Sector mapping for Indian equity market
# Covers the most common holdings across Indian mutual funds

STOCK_SECTORS = {
    # ── BANKING & FINANCE ──────────────────────────────────────────────
    "HDFC Bank Ltd": "Banking & Finance",
    "ICICI Bank Ltd": "Banking & Finance",
    "Kotak Mahindra Bank Ltd": "Banking & Finance",
    "Axis Bank Ltd": "Banking & Finance",
    "State Bank of India": "Banking & Finance",
    "IndusInd Bank Ltd": "Banking & Finance",
    "Bandhan Bank Ltd": "Banking & Finance",
    "Federal Bank Ltd": "Banking & Finance",
    "The Federal Bank Ltd": "Banking & Finance",
    "IDFC First Bank Ltd": "Banking & Finance",
    "Punjab National Bank": "Banking & Finance",
    "Bank of Baroda": "Banking & Finance",
    "Canara Bank": "Banking & Finance",
    "Indian Bank": "Banking & Finance",
    "Union Bank of India": "Banking & Finance",
    "Bank of India": "Banking & Finance",
    "Yes Bank Ltd": "Banking & Finance",
    "RBL Bank Ltd": "Banking & Finance",
    "City Union Bank Ltd": "Banking & Finance",
    "Karur Vysya Bank Ltd": "Banking & Finance",
    "South Indian Bank Ltd": "Banking & Finance",
    "Karnataka Bank Ltd": "Banking & Finance",
    "CSB Bank Ltd": "Banking & Finance",
    "DCB Bank Ltd": "Banking & Finance",
    "Bajaj Finance Ltd": "Banking & Finance",
    "Bajaj Finserv Ltd": "Banking & Finance",
    "Muthoot Finance Ltd": "Banking & Finance",
    "Manappuram Finance Ltd": "Banking & Finance",
    "Cholamandalam Investment and Finance Company Ltd": "Banking & Finance",
    "Chola Investment And Finance Company Ltd": "Banking & Finance",
    "Shriram Finance Ltd": "Banking & Finance",
    "Shriram Transport Finance Company Ltd": "Banking & Finance",
    "L&T Finance Holdings Ltd": "Banking & Finance",
    "L&T Finance Ltd": "Banking & Finance",
    "Piramal Enterprises Ltd": "Banking & Finance",
    "IIFL Finance Ltd": "Banking & Finance",
    "IIFL Wealth Management Ltd": "Banking & Finance",
    "Five-Star Business Finance Ltd": "Banking & Finance",
    "Mas Financial Services Ltd": "Banking & Finance",
    "Aptus Value Housing Finance India Ltd": "Banking & Finance",
    "Home First Finance Company India Ltd": "Banking & Finance",
    "Aavas Financiers Ltd": "Banking & Finance",
    "Mahindra & Mahindra Financial Services Ltd": "Banking & Finance",
    "Sundaram Finance Ltd": "Banking & Finance",
    "Power Finance Corporation Ltd": "Banking & Finance",
    "REC Ltd": "Banking & Finance",
    "HDFC Ltd": "Banking & Finance",
    "LIC Housing Finance Ltd": "Banking & Finance",
    "PNB Housing Finance Ltd": "Banking & Finance",
    "Can Fin Homes Ltd": "Banking & Finance",
    "ICICI Prudential Life Insurance Company Ltd": "Banking & Finance",
    "HDFC Life Insurance Company Ltd": "Banking & Finance",
    "SBI Life Insurance Company Ltd": "Banking & Finance",
    "Max Financial Services Ltd": "Banking & Finance",
    "Star Health and Allied Insurance Company Ltd": "Banking & Finance",
    "ICICI Lombard General Insurance Co Ltd": "Banking & Finance",
    "Go Digit General Insurance Ltd": "Banking & Finance",
    "SBI Cards and Payment Services Ltd": "Banking & Finance",
    "One97 Communications Ltd": "Banking & Finance",
    "Paytm": "Banking & Finance",
    "CreditAccess Grameen Ltd": "Banking & Finance",
    "Spandana Sphoorty Financial Ltd": "Banking & Finance",
    "Ujjivan Small Finance Bank Ltd": "Banking & Finance",
    "AU Small Finance Bank Ltd": "Banking & Finance",
    "Equitas Small Finance Bank Ltd": "Banking & Finance",
    "Suryoday Small Finance Bank Ltd": "Banking & Finance",
    "BSE Ltd": "Banking & Finance",
    "MCX India Ltd": "Banking & Finance",
    "CDSL Ltd": "Banking & Finance",
    "Central Depository Services India Ltd": "Banking & Finance",
    "Angel One Ltd": "Banking & Finance",
    "Nuvama Wealth Management Ltd": "Banking & Finance",
    "360 ONE WAM Ltd": "Banking & Finance",
    "Nippon Life India Asset Management Ltd": "Banking & Finance",
    "UTI Asset Management Company Ltd": "Banking & Finance",
    "CAMS": "Banking & Finance",
    "Computer Age Management Services Ltd": "Banking & Finance",
    "Fino Payments Bank Ltd": "Banking & Finance",

    # ── INFORMATION TECHNOLOGY ─────────────────────────────────────────
    "Tata Consultancy Services Ltd": "IT & Technology",
    "Infosys Ltd": "IT & Technology",
    "HCL Technologies Ltd": "IT & Technology",
    "Wipro Ltd": "IT & Technology",
    "Tech Mahindra Ltd": "IT & Technology",
    "LTIMindtree Ltd": "IT & Technology",
    "Mphasis Ltd": "IT & Technology",
    "Coforge Ltd": "IT & Technology",
    "Persistent Systems Ltd": "IT & Technology",
    "Hexaware Technologies Ltd": "IT & Technology",
    "KPIT Technologies Ltd": "IT & Technology",
    "Cyient Ltd": "IT & Technology",
    "Oracle Financial Services Software Ltd": "IT & Technology",
    "Tata Elxsi Ltd": "IT & Technology",
    "Zensar Technologies Ltd": "IT & Technology",
    "Mastek Ltd": "IT & Technology",
    "Birlasoft Ltd": "IT & Technology",
    "Sonata Software Ltd": "IT & Technology",
    "FSL - Firstsource Solutions Ltd": "IT & Technology",
    "Firstsource Solutions Ltd": "IT & Technology",
    "Rategain Travel Technologies Ltd": "IT & Technology",
    "Netweb Technologies India Ltd": "IT & Technology",
    "Data Patterns India Ltd": "IT & Technology",
    "NIIT Technologies Ltd": "IT & Technology",
    "Tanla Platforms Ltd": "IT & Technology",
    "Newgen Software Technologies Ltd": "IT & Technology",
    "Kellton Tech Solutions Ltd": "IT & Technology",
    "Saksoft Ltd": "IT & Technology",
    "Intellect Design Arena Ltd": "IT & Technology",
    "Nucleus Software Exports Ltd": "IT & Technology",
    "Happiest Minds Technologies Ltd": "IT & Technology",
    "Route Mobile Ltd": "IT & Technology",
    "Indiamart Intermesh Ltd": "IT & Technology",
    "IndiaMART InterMESH Ltd": "IT & Technology",
    "Info Edge India Ltd": "IT & Technology",
    "Naukri": "IT & Technology",
    "Zomato Ltd": "Consumer Discretionary",
    "Swiggy Ltd": "Consumer Discretionary",

    # ── OIL, GAS & ENERGY ──────────────────────────────────────────────
    "Reliance Industries Ltd": "Oil, Gas & Energy",
    "ONGC Ltd": "Oil, Gas & Energy",
    "Oil and Natural Gas Corporation Ltd": "Oil, Gas & Energy",
    "BPCL Ltd": "Oil, Gas & Energy",
    "Bharat Petroleum Corporation Ltd": "Oil, Gas & Energy",
    "Indian Oil Corporation Ltd": "Oil, Gas & Energy",
    "HPCL Ltd": "Oil, Gas & Energy",
    "Hindustan Petroleum Corporation Ltd": "Oil, Gas & Energy",
    "Petronet LNG Ltd": "Oil, Gas & Energy",
    "GAIL India Ltd": "Oil, Gas & Energy",
    "Indraprastha Gas Ltd": "Oil, Gas & Energy",
    "Mahanagar Gas Ltd": "Oil, Gas & Energy",
    "Gujarat Gas Ltd": "Oil, Gas & Energy",
    "Gujarat State Petronet Ltd": "Oil, Gas & Energy",
    "Adani Total Gas Ltd": "Oil, Gas & Energy",
    "Aegis Logistics Ltd": "Oil, Gas & Energy",
    "Castrol India Ltd": "Oil, Gas & Energy",
    "Chennai Petroleum Corporation Ltd": "Oil, Gas & Energy",

    # ── POWER & UTILITIES ──────────────────────────────────────────────
    "NTPC Ltd": "Power & Utilities",
    "Power Grid Corporation of India Ltd": "Power & Utilities",
    "Tata Power Company Ltd": "Power & Utilities",
    "Adani Power Ltd": "Power & Utilities",
    "Adani Green Energy Ltd": "Power & Utilities",
    "Torrent Power Ltd": "Power & Utilities",
    "CESC Ltd": "Power & Utilities",
    "JSW Energy Ltd": "Power & Utilities",
    "NHPC Ltd": "Power & Utilities",
    "SJVN Ltd": "Power & Utilities",
    "Kalpataru Projects International Ltd": "Power & Utilities",
    "KEC International Ltd": "Power & Utilities",
    "Thermax Ltd": "Power & Utilities",
    "Triveni Engineering & Industries Ltd": "Power & Utilities",
    "Suzlon Energy Ltd": "Power & Utilities",
    "Inox Wind Ltd": "Power & Utilities",
    "Waaree Energies Ltd": "Power & Utilities",
    "Premier Energies Ltd": "Power & Utilities",
    "Sterling and Wilson Renewable Energy Ltd": "Power & Utilities",
    "Talwandi Sabo Power Limited": "Power & Utilities",

    # ── CONSUMER STAPLES / FMCG ────────────────────────────────────────
    "Hindustan Unilever Ltd": "Consumer Staples",
    "ITC Ltd": "Consumer Staples",
    "Nestle India Ltd": "Consumer Staples",
    "Britannia Industries Ltd": "Consumer Staples",
    "Dabur India Ltd": "Consumer Staples",
    "Marico Ltd": "Consumer Staples",
    "Godrej Consumer Products Ltd": "Consumer Staples",
    "Colgate-Palmolive India Ltd": "Consumer Staples",
    "Emami Ltd": "Consumer Staples",
    "Bajaj Consumer Care Ltd": "Consumer Staples",
    "Tata Consumer Products Ltd": "Consumer Staples",
    "Varun Beverages Ltd": "Consumer Staples",
    "United Spirits Ltd": "Consumer Staples",
    "United Breweries Ltd": "Consumer Staples",
    "Radico Khaitan Ltd": "Consumer Staples",
    "Mrs. Bectors Food Specialities Ltd": "Consumer Staples",
    "Bikaji Foods International Ltd": "Consumer Staples",
    "Patanjali Foods Ltd": "Consumer Staples",
    "Jyothy Labs Ltd": "Consumer Staples",
    "Vinati Organics Ltd": "Chemicals",
    "Pidilite Industries Ltd": "Chemicals",

    # ── CONSUMER DISCRETIONARY ─────────────────────────────────────────
    "Titan Company Ltd": "Consumer Discretionary",
    "Trent Ltd": "Consumer Discretionary",
    "Avenue Supermarts Ltd": "Consumer Discretionary",
    "D-Mart": "Consumer Discretionary",
    "Vedant Fashions Ltd": "Consumer Discretionary",
    "Manyavar": "Consumer Discretionary",
    "Bata India Ltd": "Consumer Discretionary",
    "Relaxo Footwears Ltd": "Consumer Discretionary",
    "Campus Activewear Ltd": "Consumer Discretionary",
    "Sapphire Foods India Ltd": "Consumer Discretionary",
    "Devyani International Ltd": "Consumer Discretionary",
    "Westlife Foodworld Ltd": "Consumer Discretionary",
    "Jubilant Foodworks Ltd": "Consumer Discretionary",
    "Restaurant Brands Asia Ltd": "Consumer Discretionary",
    "Delhivery Ltd": "Consumer Discretionary",
    "Eicher Motors Ltd": "Automobile & Auto Ancillaries",
    "Maruti Suzuki India Ltd": "Automobile & Auto Ancillaries",
    "Tata Motors Ltd": "Automobile & Auto Ancillaries",
    "Mahindra & Mahindra Ltd": "Automobile & Auto Ancillaries",
    "Hero MotoCorp Ltd": "Automobile & Auto Ancillaries",
    "Bajaj Auto Ltd": "Automobile & Auto Ancillaries",
    "TVS Motor Company Ltd": "Automobile & Auto Ancillaries",
    "Ashok Leyland Ltd": "Automobile & Auto Ancillaries",
    "Escorts Kubota Ltd": "Automobile & Auto Ancillaries",
    "Force Motors Ltd": "Automobile & Auto Ancillaries",
    "Olectra Greentech Ltd": "Automobile & Auto Ancillaries",
    "Ola Electric Mobility Ltd": "Automobile & Auto Ancillaries",

    # ── AUTO ANCILLARIES ───────────────────────────────────────────────
    "Bosch Ltd": "Automobile & Auto Ancillaries",
    "Motherson Sumi Wiring India Ltd": "Automobile & Auto Ancillaries",
    "Samvardhana Motherson International Ltd": "Automobile & Auto Ancillaries",
    "Bharat Forge Ltd": "Automobile & Auto Ancillaries",
    "Balkrishna Industries Ltd": "Automobile & Auto Ancillaries",
    "MRF Ltd": "Automobile & Auto Ancillaries",
    "Apollo Tyres Ltd": "Automobile & Auto Ancillaries",
    "CEAT Ltd": "Automobile & Auto Ancillaries",
    "Endurance Technologies Ltd": "Automobile & Auto Ancillaries",
    "Minda Industries Ltd": "Automobile & Auto Ancillaries",
    "Uno Minda Ltd": "Automobile & Auto Ancillaries",
    "Sona BLW Precision Forgings Ltd": "Automobile & Auto Ancillaries",
    "Timken India Ltd": "Automobile & Auto Ancillaries",
    "Schaeffler India Ltd": "Automobile & Auto Ancillaries",
    "SKF India Ltd": "Automobile & Auto Ancillaries",
    "Tube Investments of India Ltd": "Automobile & Auto Ancillaries",
    "Tube Investments of India Ltd Ordinary Shares": "Automobile & Auto Ancillaries",
    "Suprajit Engineering Ltd": "Automobile & Auto Ancillaries",
    "Sandhar Technologies Ltd": "Automobile & Auto Ancillaries",
    "Craftsman Automation Ltd": "Automobile & Auto Ancillaries",
    "Atul Auto Ltd": "Automobile & Auto Ancillaries",
    "Gabriel India Ltd": "Automobile & Auto Ancillaries",
    "Minda Corporation Ltd": "Automobile & Auto Ancillaries",

    # ── PHARMA & HEALTHCARE ────────────────────────────────────────────
    "Sun Pharmaceutical Industries Ltd": "Pharma & Healthcare",
    "Dr Reddys Laboratories Ltd": "Pharma & Healthcare",
    "Cipla Ltd": "Pharma & Healthcare",
    "Divi's Laboratories Ltd": "Pharma & Healthcare",
    "Mankind Pharma Ltd": "Pharma & Healthcare",
    "Lupin Ltd": "Pharma & Healthcare",
    "Aurobindo Pharma Ltd": "Pharma & Healthcare",
    "Zydus Lifesciences Ltd": "Pharma & Healthcare",
    "Alkem Laboratories Ltd": "Pharma & Healthcare",
    "Torrent Pharmaceuticals Ltd": "Pharma & Healthcare",
    "Ipca Laboratories Ltd": "Pharma & Healthcare",
    "Gland Pharma Ltd": "Pharma & Healthcare",
    "Biocon Ltd": "Pharma & Healthcare",
    "Abbott India Ltd": "Pharma & Healthcare",
    "Pfizer Ltd": "Pharma & Healthcare",
    "Sanofi India Ltd": "Pharma & Healthcare",
    "Glaxosmithkline Pharmaceuticals Ltd": "Pharma & Healthcare",
    "JB Chemicals & Pharmaceuticals Ltd": "Pharma & Healthcare",
    "Natco Pharma Ltd": "Pharma & Healthcare",
    "Ajanta Pharma Ltd": "Pharma & Healthcare",
    "Laurus Labs Ltd": "Pharma & Healthcare",
    "Granules India Ltd": "Pharma & Healthcare",
    "Suven Pharmaceuticals Ltd": "Pharma & Healthcare",
    "Solara Active Pharma Sciences Ltd": "Pharma & Healthcare",
    "Sequent Scientific Ltd": "Pharma & Healthcare",
    "Shalby Ltd": "Pharma & Healthcare",
    "Krishna Institute of Medical Sciences Ltd": "Pharma & Healthcare",
    "Narayana Hrudayalaya Ltd": "Pharma & Healthcare",
    "Max Healthcare Institute Ltd": "Pharma & Healthcare",
    "Apollo Hospitals Enterprise Ltd": "Pharma & Healthcare",
    "Fortis Healthcare Ltd": "Pharma & Healthcare",
    "Medplus Health Services Ltd": "Pharma & Healthcare",
    "Metropolis Healthcare Ltd": "Pharma & Healthcare",
    "Dr Lal Pathlabs Ltd": "Pharma & Healthcare",
    "Vijaya Diagnostic Centre Ltd": "Pharma & Healthcare",
    "Thyrocare Technologies Ltd": "Pharma & Healthcare",
    "Poly Medicure Ltd": "Pharma & Healthcare",
    "Syngene International Ltd": "Pharma & Healthcare",
    "Divi Laboratories": "Pharma & Healthcare",

    # ── METALS & MINING ────────────────────────────────────────────────
    "Tata Steel Ltd": "Metals & Mining",
    "JSW Steel Ltd": "Metals & Mining",
    "Hindalco Industries Ltd": "Metals & Mining",
    "Vedanta Ltd": "Metals & Mining",
    "Steel Authority of India Ltd": "Metals & Mining",
    "National Aluminium Company Ltd": "Metals & Mining",
    "Hindustan Zinc Ltd": "Metals & Mining",
    "Hindustan Copper Ltd": "Metals & Mining",
    "NMDC Ltd": "Metals & Mining",
    "Coal India Ltd": "Metals & Mining",
    "APL Apollo Tubes Ltd": "Metals & Mining",
    "Jindal Steel & Power Ltd": "Metals & Mining",
    "Jindal Stainless Ltd": "Metals & Mining",
    "Welspun Corp Ltd": "Metals & Mining",
    "Ratnamani Metals & Tubes Ltd": "Metals & Mining",
    "Mishra Dhatu Nigam Ltd": "Metals & Mining",
    "MOIL Ltd": "Metals & Mining",
    "Gravita India Ltd": "Metals & Mining",
    "Vedanta Aluminium Metal Limited": "Metals & Mining",
    "Vedanta Iron And Steel Limited": "Metals & Mining",
    "Malco Energy Limited": "Metals & Mining",

    # ── CAPITAL GOODS & INDUSTRIALS ────────────────────────────────────
    "Larsen & Toubro Ltd": "Capital Goods",
    "Siemens Ltd": "Capital Goods",
    "ABB India Ltd": "Capital Goods",
    "Honeywell Automation India Ltd": "Capital Goods",
    "Bharat Heavy Electricals Ltd": "Capital Goods",
    "BHEL": "Capital Goods",
    "Cummins India Ltd": "Capital Goods",
    "Bharat Electronics Ltd": "Capital Goods",
    "HAL Ltd": "Capital Goods",
    "Hindustan Aeronautics Ltd": "Capital Goods",
    "Hindustan Aeronautics Ltd Ordinary Shares": "Capital Goods",
    "Mazagon Dock Shipbuilders Ltd": "Capital Goods",
    "Cochin Shipyard Ltd": "Capital Goods",
    "Garden Reach Shipbuilders & Engineers Ltd": "Capital Goods",
    "BEML Ltd": "Capital Goods",
    "Triveni Turbine Ltd": "Capital Goods",
    "Elecon Engineering Company Ltd": "Capital Goods",
    "Grindwell Norton Ltd": "Capital Goods",
    "Kaynes Technology India Ltd": "Capital Goods",
    "Dixon Technologies India Ltd": "Capital Goods",
    "Amber Enterprises India Ltd": "Capital Goods",
    "Voltamp Transformers Ltd": "Capital Goods",
    "INOX India Ltd": "Capital Goods",
    "Carborundum Universal Ltd": "Capital Goods",
    "CG Power and Industrial Solutions Ltd": "Capital Goods",
    "Kirloskar Brothers Ltd": "Capital Goods",
    "Kirloskar Electric Company Ltd": "Capital Goods",
    "Kennametal India Ltd": "Capital Goods",
    "TD Power Systems Ltd": "Capital Goods",
    "Skipper Ltd": "Capital Goods",
    "Transformers and Rectifiers India Ltd": "Capital Goods",
    "Apar Industries Ltd": "Capital Goods",
    "Polycab India Ltd": "Capital Goods",
    "KEI Industries Ltd": "Capital Goods",
    "Havells India Ltd": "Capital Goods",
    "V-Guard Industries Ltd": "Capital Goods",
    "Crompton Greaves Consumer Electricals Ltd": "Capital Goods",
    "Orient Electric Ltd": "Capital Goods",
    "Finolex Cables Ltd": "Capital Goods",

    # ── CEMENT & CONSTRUCTION ──────────────────────────────────────────
    "Ultratech Cement Ltd": "Cement & Construction",
    "Shree Cement Ltd": "Cement & Construction",
    "Ambuja Cements Ltd": "Cement & Construction",
    "ACC Ltd": "Cement & Construction",
    "Dalmia Bharat Ltd": "Cement & Construction",
    "The Ramco Cements Ltd": "Cement & Construction",
    "JK Cement Ltd": "Cement & Construction",
    "JK Lakshmi Cement Ltd": "Cement & Construction",
    "Birla Corporation Ltd": "Cement & Construction",
    "India Cements Ltd": "Cement & Construction",
    "Nuvoco Vistas Corporation Ltd": "Cement & Construction",
    "Sagar Cements Ltd": "Cement & Construction",
    "DLF Ltd": "Cement & Construction",
    "Prestige Estates Projects Ltd": "Cement & Construction",
    "Godrej Properties Ltd": "Cement & Construction",
    "Oberoi Realty Ltd": "Cement & Construction",
    "Macrotech Developers Ltd": "Cement & Construction",
    "Lodha": "Cement & Construction",
    "Phoenix Mills Ltd": "Cement & Construction",
    "Brigade Enterprises Ltd": "Cement & Construction",
    "Sobha Ltd": "Cement & Construction",
    "Puravankara Ltd": "Cement & Construction",
    "Kolte-Patil Developers Ltd": "Cement & Construction",
    "Nuvama": "Cement & Construction",
    "Anant Raj Ltd": "Cement & Construction",
    "NCC Ltd": "Cement & Construction",
    "J Kumar Infraprojects Ltd": "Cement & Construction",
    "PNC Infratech Ltd": "Cement & Construction",
    "HG Infra Engineering Ltd": "Cement & Construction",
    "Dilip Buildcon Ltd": "Cement & Construction",
    "PSP Projects Ltd": "Cement & Construction",

    # ── CHEMICALS ──────────────────────────────────────────────────────
    "Asian Paints Ltd": "Chemicals",
    "Berger Paints India Ltd": "Chemicals",
    "Kansai Nerolac Paints Ltd": "Chemicals",
    "Akzo Nobel India Ltd": "Chemicals",
    "Atul Ltd": "Chemicals",
    "SRF Ltd": "Chemicals",
    "Navin Fluorine International Ltd": "Chemicals",
    "Deepak Nitrite Ltd": "Chemicals",
    "Tata Chemicals Ltd": "Chemicals",
    "UPL Ltd": "Chemicals",
    "Bayer CropScience Ltd": "Chemicals",
    "PI Industries Ltd": "Chemicals",
    "Rallis India Ltd": "Chemicals",
    "Sumitomo Chemical India Ltd": "Chemicals",
    "Balaji Amines Ltd": "Chemicals",
    "Gujarat Fluorochemicals Ltd": "Chemicals",
    "Sudarshan Chemical Industries Ltd": "Chemicals",
    "Fine Organic Industries Ltd": "Chemicals",
    "Galaxy Surfactants Ltd": "Chemicals",
    "Rossari Biotech Ltd": "Chemicals",
    "Anupam Rasayan India Ltd": "Chemicals",
    "Laxmi Organic Industries Ltd": "Chemicals",
    "Tatva Chintan Pharma Chem Ltd": "Chemicals",
    "Clean Science and Technology Ltd": "Chemicals",
    "Nocil Ltd": "Chemicals",
    "Camlin Fine Sciences Ltd": "Chemicals",
    "Neogen Chemicals Ltd": "Chemicals",
    "Paushak Ltd": "Chemicals",
    "Meghmani Finechem Ltd": "Chemicals",
    "Chemplast Sanmar Ltd": "Chemicals",
    "Prince Pipes and Fittings Ltd": "Chemicals",
    "Supreme Industries Ltd": "Chemicals",
    "Astral Ltd": "Chemicals",
    "Finolex Industries Ltd": "Chemicals",

    # ── TELECOM ────────────────────────────────────────────────────────
    "Bharti Airtel Ltd": "Telecom",
    "Vodafone Idea Ltd": "Telecom",
    "Tata Communications Ltd": "Telecom",
    "MTNL": "Telecom",
    "Sterlite Technologies Ltd": "Telecom",
    "Tejas Networks Ltd": "Telecom",
    "HFCL Ltd": "Telecom",
    "ITI Ltd": "Telecom",

    # ── MEDIA & ENTERTAINMENT ──────────────────────────────────────────
    "Zee Entertainment Enterprises Ltd": "Media & Entertainment",
    "Sun TV Network Ltd": "Media & Entertainment",
    "PVR INOX Ltd": "Media & Entertainment",
    "Dish TV India Ltd": "Media & Entertainment",
    "Tips Music Ltd": "Media & Entertainment",
    "Nazara Technologies Ltd": "Media & Entertainment",

    # ── LOGISTICS & TRANSPORT ──────────────────────────────────────────
    "Container Corporation of India Ltd": "Logistics & Transport",
    "Blue Dart Express Ltd": "Logistics & Transport",
    "Mahindra Logistics Ltd": "Logistics & Transport",
    "TCI Express Ltd": "Logistics & Transport",
    "Transport Corporation of India Ltd": "Logistics & Transport",
    "VRL Logistics Ltd": "Logistics & Transport",
    "Allcargo Logistics Ltd": "Logistics & Transport",
    "Allcargo Global Ltd": "Logistics & Transport",
    "Gati Ltd": "Logistics & Transport",
    "Shadowfax Technologies Ltd": "Logistics & Transport",
    "Adani Ports and Special Economic Zone Ltd": "Logistics & Transport",
    "Gujarat Pipavav Port Ltd": "Logistics & Transport",
    "JSW Infrastructure Ltd": "Logistics & Transport",
    "Interglobe Aviation Ltd": "Logistics & Transport",
    "IndiGo": "Logistics & Transport",
    "SpiceJet Ltd": "Logistics & Transport",
    "Indian Railway Finance Corporation Ltd": "Logistics & Transport",
    "IRCTC Ltd": "Logistics & Transport",
    "Rail Vikas Nigam Ltd": "Logistics & Transport",
    "RITES Ltd": "Logistics & Transport",
    "IRCON International Ltd": "Logistics & Transport",
    "Texmaco Rail & Engineering Ltd": "Logistics & Transport",

    # ── AGRICULTURE & AGRI-INPUTS ──────────────────────────────────────
    "Kaveri Seed Company Ltd": "Agriculture",
    "Avanti Feeds Ltd": "Agriculture",
    "Waterbase Ltd": "Agriculture",
    "EID Parry India Ltd": "Agriculture",
    "Balrampur Chini Mills Ltd": "Agriculture",
    "Triveni Engineering & Industries Ltd": "Agriculture",
    "Dhanuka Agritech Ltd": "Agriculture",
    "Coromandel International Ltd": "Agriculture",
    "Chambal Fertilizers & Chemicals Ltd": "Agriculture",
    "Deepak Fertilisers and Petrochemicals Corporation Ltd": "Agriculture",
    "Zuari Agro Chemicals Ltd": "Agriculture",
    "National Fertilizers Ltd": "Agriculture",
    "Rashtriya Chemicals & Fertilizers Ltd": "Agriculture",

    # ── RETAIL & E-COMMERCE ────────────────────────────────────────────
    "Nykaa": "Consumer Discretionary",
    "FSN E-Commerce Ventures Ltd": "Consumer Discretionary",
    "Shoppers Stop Ltd": "Consumer Discretionary",
    "V-Mart Retail Ltd": "Consumer Discretionary",
    "Aditya Birla Fashion and Retail Ltd": "Consumer Discretionary",
    "Landmark Cars Ltd": "Consumer Discretionary",
    "Ethos Ltd": "Consumer Discretionary",
    "PC Jeweller Ltd": "Consumer Discretionary",
    "Kalyan Jewellers India Ltd": "Consumer Discretionary",
    "Senco Gold Ltd": "Consumer Discretionary",
    "Thangamayil Jewellery Ltd": "Consumer Discretionary",

    # ── HOSPITALITY & TOURISM ──────────────────────────────────────────
    "Indian Hotels Company Ltd": "Hospitality",
    "EIH Ltd": "Hospitality",
    "Lemon Tree Hotels Ltd": "Hospitality",
    "Chalet Hotels Ltd": "Hospitality",
    "Mahindra Holidays & Resorts India Ltd": "Hospitality",
    "Thomas Cook India Ltd": "Hospitality",

    # ── DIVERSIFIED / CONGLOMERATES ────────────────────────────────────
    "Adani Enterprises Ltd": "Diversified",
    "Adani Ports and Special Economic Zone Ltd": "Diversified",
    "Tata Investment Corporation Ltd": "Diversified",
    "3M India Ltd": "Diversified",
    "Honeywell": "Diversified",
}

# Keyword fallback rules — applied when exact match fails
SECTOR_KEYWORDS = [
    (["bank", "finance", "nbfc", "financial", "insurance", "capital", "invest", "wealth", "credit", "lending", "microfinance", "housing finance", "payment"], "Banking & Finance"),
    (["tech", "software", "infosys", "tcs", "wipro", "hcl", "digital", "it ", "information", "systems", "data", "cyber", "cloud", "saas"], "IT & Technology"),
    (["pharma", "drug", "medic", "health", "hospital", "clinic", "diagnostic", "lab", "biocon", "life science", "therapeut"], "Pharma & Healthcare"),
    (["petro", "oil", "gas", "fuel", "refin", "lng", "bpcl", "hpcl", "ongc"], "Oil, Gas & Energy"),
    (["power", "energy", "solar", "wind", "electric", "ntpc", "hydro", "grid", "utility"], "Power & Utilities"),
    (["cement", "real estate", "realty", "infra", "construct", "builder", "developer", "housing"], "Cement & Construction"),
    (["steel", "metal", "alumin", "copper", "zinc", "iron", "mining", "coal", "mineral"], "Metals & Mining"),
    (["auto", "motor", "vehicle", "tyre", "axle", "gear", "engine", "car", "truck", "bus", "ev "], "Automobile & Auto Ancillaries"),
    (["chemical", "paint", "agrochem", "pesticide", "fertilizer", "plastic", "polymer", "pigment"], "Chemicals"),
    (["fmcg", "consumer", "food", "beverage", "soap", "detergent", "personal care", "biscuit", "dairy"], "Consumer Staples"),
    (["telecom", "airtel", "jio", "vodafone", "telecom", "network", "wireless", "broadband"], "Telecom"),
    (["textile", "garment", "apparel", "fabric", "yarn", "cotton", "wool", "fiber"], "Textiles"),
    (["logistics", "transport", "shipping", "freight", "cargo", "courier", "port", "aviation", "airline", "railway", "rail"], "Logistics & Transport"),
    (["media", "entertainment", "film", "movie", "television", "broadcast", "ott"], "Media & Entertainment"),
    (["hotel", "hospitality", "resort", "tourism", "travel", "restaurant"], "Hospitality"),
    (["retail", "mall", "e-commerce", "jewel", "fashion", "apparel"], "Consumer Discretionary"),
    (["capital goods", "engineering", "industrial", "machinery", "equipment", "defence", "defence", "shipbuild", "aerospace"], "Capital Goods"),
    (["agri", "seed", "crop", "farm", "harvest", "sugar", "irrigation"], "Agriculture"),
]


def get_sector(stock_name: str) -> str:
    """Return the sector for a given stock name."""
    # Exact match first
    if stock_name in STOCK_SECTORS:
        return STOCK_SECTORS[stock_name]

    # Partial match in dict keys
    sl = stock_name.lower()
    for key, sector in STOCK_SECTORS.items():
        if key.lower() in sl or sl in key.lower():
            return sector

    # Keyword fallback
    for keywords, sector in SECTOR_KEYWORDS:
        for kw in keywords:
            if kw in sl:
                return sector

    return "Others"
